.gitignore, DevOps/README.md, DevOps/deploy-keyvault.ps1, DevOps/deploy-local.ps1, DevOps/deploy-template.ps1, DevOps/deploy.ps1, DevOps/infrastructure.json, DevOps/infrastructure.parameters.dev.json, DevOps/setup-servicePrinciple.ps1
* add powershell scripts to setup service principal, log into azure, deploy the ARM template, and deploy KeyVault with secrets and access polices
* add a README for the team
* updated gitIgnore
=> * add ARM templates to describe all the resources we need

DevOps/infrastructure.json, DevOps/infrastructure.parameters.dev.json
Implements [AB#43386](https://ssw.visualstudio.com/dacc617d-2dc5-4f9e-aa12-ece4e4fe66b7/_workitems/edit/43386) - Provision SQL resources
=> add sql server and database to ARM templates

API/SSW.Consulting.Application/Common/Interfaces/ICurrentUserService.cs, API/SSW.Consulting.Application/Leaderboard/Queries/GetLeaderboardList/GetLeaderboardListQuery.cs, API/SSW.Consulting.Application/User/Queries/GetCurrentUser/AutoMapperProfile.cs, API/SSW.Consulting.Application/User/Queries/GetCurrentUser/GetCurrentUserQuery.cs, API/SSW.Consulting.Application/User/Queries/GetCurrentUser/UserViewModel.cs, API/SSW.Consulting.Application/User/Queries/GetUser/GetUserQuery.cs, API/SSW.Consulting/Controllers/UserController.cs, API/SSW.Consulting/Services/CurrentUserService.cs, API/SSW.Consulting/wwwroot/api/specification.json, Xamarin/SSW.Consulting/SSW.Consulting/Helpers/ApiClient.g.cs
modified leaderboard query to prevent user email leak
=> added endpoint to send back the currently logged in user's details

API/SSW.Consulting.Application/Common/Behaviours/RequestPerformanceBehaviour.cs, API/SSW.Consulting/Program.cs, API/SSW.Consulting/SSW.Consulting.WebAPI.csproj, API/SSW.Consulting/Startup.cs, API/SSW.Consulting/serilog.appinsights.json, API/SSW.Consulting/serilog.async.console.json, API/SSW.Consulting/serilog.seq.json
implements [AB#43385](https://ssw.visualstudio.com/dacc617d-2dc5-4f9e-aa12-ece4e4fe66b7/_workitems/edit/43385)
* add serilog with minimal code config
* added sample configs for the team to use in their own secrets.json file when working locally
=> 43385 add logging

Xamarin/SSW.Consulting/SSW.Consulting/AppShell.xaml.cs, Xamarin/SSW.Consulting/SSW.Consulting/Services/IUserService.cs, Xamarin/SSW.Consulting/SSW.Consulting/Services/MockUserService.cs, Xamarin/SSW.Consulting/SSW.Consulting/Services/UserService.cs
+ refactored sign-out async code
build passed https://ssw.visualstudio.com/SSW.Consulting/_build/results?buildId=16112
=> signOutAsync refactored to SignOut

Xamarin/SSW.Consulting/SSW.Consulting.Android/Properties/AndroidManifest.xml, Xamarin/SSW.Consulting/SSW.Consulting/Views/LeaderBoard.xaml.cs
=> resolved leaderboard search bug on android

LICENSE
Added a license as per the rule:
https://rules.ssw.com.au/do-you-know-the-correct-license-to-use-for-open-source-software
=> Add apache license

API/SSW.Consulting/Startup.cs, API/SSW.Consulting/appsettings.json
changed code to configure CORS policy
=> Admin auth

API/SSW.Consulting/Startup.cs
.AllowAnyHeader()
.AllowAnyMethod()
.AllowCredentials();
=> Added extra config to CORS policy

API/SSW.Rewards.Application/SSW.Rewards.Application.csproj
=> committed csproj

API/SSW.Rewards.postman_collection.json
Load the SSW.Rewards postman collection into Postman and start testing :)
=> add a postman collection for entire Rewards API

API/SSW.Rewards.Application/System/Commands/SeedData/SampleDataSeeder.cs
Added @jernejk 's user group talk
=> Rewards - added "From Paper to Power using Azure Form Recognition"

API/SSW.Rewards.Application/System/Commands/SeedData/SampleDataSeeder.cs
-Add Clean Architecture SuperPower for May 2020
-Add Angular SuperPower for May 2020
=> Added SuperPowers for May

API/SSW.Rewards.Application/System/Commands/SeedData/SampleDataSeeder.cs
=> add AI Hack Day online - june 2020

API/SSW.Rewards.Application/System/Commands/SeedData/SampleDataSeeder.cs
=> Add Xamarin Hack Day July 2020

API/SSW.Rewards.Application/Reward/Commands/ClaimReward/ClaimRewardCommand.cs
Updates a comment to reflect tech debt and link back to #100
=> updated tech debt comment

API/SSW.Rewards.Application/Common/Extensions/UserExtensions.cs, API/SSW.Rewards.Application/Staff/Commands/UpsertStaffMemberProfile/UpsertStaffMemberProfileCommand.cs, API/SSW.Rewards.Application/Staff/Queries/GetStaffMemberProfile/GetStaffMemberProfileQuery.cs, API/SSW.Rewards.Application/System/Commands/SeedData/SampleDataSeeder.cs, API/SSW.Rewards.Application/User/Queries/GetCurrentUser/CurrentUserViewModel.cs, API/SSW.Rewards.Application/User/Queries/GetCurrentUser/GetCurrentUserQuery.cs, API/SSW.Rewards.Domain/Entities/Achievement.cs, API/SSW.Rewards.Domain/Entities/StaffMember.cs, API/SSW.Rewards.Persistence/Migrations/20220406012550_LinkAchievementsAndStaff.Designer.cs, API/SSW.Rewards.Persistence/Migrations/20220406012550_LinkAchievementsAndStaff.cs, API/SSW.Rewards.Persistence/SSWRewardsDbContext.cs, API/SSW.Rewards/Controllers/AdminTestController.cs, API/SSW.Rewards/Controllers/SeedController.cs, API/SSW.Rewards/Controllers/StaffController.cs, API/SSW.Rewards/Program.cs, API/SSW.Rewards/nswag/SSW-Rewards-client.ts, API/SSW.Rewards/wwwroot/api/specification.json, Xamarin/SSW.Rewards/SSW.Rewards.Android/SSW.Rewards.Android.csproj, Xamarin/SSW.Rewards/SSW.Rewards/App.xaml.cs, Xamarin/SSW.Rewards/SSW.Rewards/AppShell.xaml, Xamarin/SSW.Rewards/SSW.Rewards/AppShell.xaml.cs, Xamarin/SSW.Rewards/SSW.Rewards/Constants.cs, Xamarin/SSW.Rewards/SSW.Rewards/Helpers/ApiClient.g.cs, Xamarin/SSW.Rewards/SSW.Rewards/PopupPages/MyQRPage.xaml, Xamarin/SSW.Rewards/SSW.Rewards/PopupPages/MyQRPage.xaml.cs, Xamarin/SSW.Rewards/SSW.Rewards/Resolver.cs, Xamarin/SSW.Rewards/SSW.Rewards/SSW.Rewards.csproj, Xamarin/SSW.Rewards/SSW.Rewards/Services/IUserService.cs, Xamarin/SSW.Rewards/SSW.Rewards/Services/UserService.cs, Xamarin/SSW.Rewards/SSW.Rewards/ViewModels/LoginPageViewModel.cs
This PR adds staff QR codes to the app. See: https://youtu.be/T6ykD_YOCWM
It also links staff logins with Achievements directly.
TODO:
=> 172 show own qr code

API/SSW.Rewards.Application/User/Queries/GetCurrentUser/GetCurrentUserQuery.cs
A Null exception was being thrown when the user who is logged in didn't have an achievement. This was effecting the current user from being able to see any records on staging. 
- Fixes formatting
- Fixes a Null Exception
=> 🐛Fix GetCurrentUserQuery 

API/SSW.Rewards.Application/Staff/Commands/UpsertStaffMemberProfile/UpsertStaffMemberProfileCommand.cs, Xamarin/SSW.Rewards/SSW.Rewards/Helpers/ApiClient.g.cs
- Fixes a bug when upserting Staff members, it was not creating them as they were always found.
=> 🐛 Fix a bug with upserting staff

Xamarin/SSW.Rewards/SSW.Rewards.Android/Properties/AndroidManifest.xml, Xamarin/SSW.Rewards/SSW.Rewards.iOS/Info.plist
Bumps the version of both iOS and Android + minor.
=> 🔖 bump iOS and Android versions

API/SSW.Rewards.Application/Staff/Commands/UpsertStaffMemberProfile/UpsertStaffMemberProfileCommand.cs, API/SSW.Rewards.Application/Staff/Queries/GetStaffList/StaffDto.cs, API/SSW.Rewards.Domain/Entities/StaffMember.cs, API/SSW.Rewards.Persistence/Migrations/20220516031104_addTwitterGitHub.Designer.cs, API/SSW.Rewards.Persistence/Migrations/20220516031104_addTwitterGitHub.cs, API/SSW.Rewards/nswag/SSW-Rewards-client.ts, API/SSW.Rewards/wwwroot/api/specification.json
- Adds GitHubUsername to the StaffMember Table
- Adds LinkedInUrl to the StaffMember Table
=> ✨ Add GitHub and LinkedIn Fields

API/SSW.Rewards.Application/DependencyInjection.cs, API/SSW.Rewards.Application/Leaderboard/Queries/GetLeaderboardList/GetLeaderboardListQuery.cs, API/SSW.Rewards.Application/Services/UserService.cs, API/SSW.Rewards.Application/Users/Commands/RegisterUser/RegisterUserCommand.cs, API/SSW.Rewards.Application/Users/Queries/GetCurrentUser/GetCurrentUserQuery.cs, API/SSW.Rewards.Domain/Entities/User.cs, API/SSW.Rewards.Persistence/Migrations/20220520050832_AddActivationToUser.Designer.cs, API/SSW.Rewards.Persistence/Migrations/20220520050832_AddActivationToUser.cs, API/SSW.Rewards/Controllers/BaseController.cs, API/SSW.Rewards/Controllers/UserController.cs, API/SSW.Rewards/appsettings.json, API/SSW.Rewards/nswag/SSW-Rewards-client.ts, API/SSW.Rewards/wwwroot/api/specification.json, Xamarin/SSW.Rewards/SSW.Rewards/Constants.cs, Xamarin/SSW.Rewards/SSW.Rewards/Helpers/ApiClient.g.cs
In this PR:
* Adds roles for IdentityServer to retrieve to inject into token
* Adds a registration endpoint for IdentityServer to register new users
* Adds an activation status for user which defaults to false, and sets to true when they log in
* Hides unactivated users from the leaderboard
Corresponding pull request in SSW Rewards: https://github.com/SSWConsulting/SSW.IdentityServer/pull/15
=> Roles and register

API/SSW.Rewards.Application/Services/UserService.cs, Xamarin/SSW.Rewards/SSW.Rewards.Android/SSW.Rewards.Android.csproj, Xamarin/SSW.Rewards/SSW.Rewards/App.xaml, Xamarin/SSW.Rewards/SSW.Rewards/Constants.cs, Xamarin/SSW.Rewards/SSW.Rewards/Controls/Notifications.xaml, Xamarin/SSW.Rewards/SSW.Rewards/Controls/RecentActivity.xaml, Xamarin/SSW.Rewards/SSW.Rewards/Pages/PeoplePage.xaml, Xamarin/SSW.Rewards/SSW.Rewards/Services/UserService.cs, Xamarin/SSW.Rewards/SSW.Rewards/ViewModels/OnBoardingViewModel.cs, Xamarin/SSW.Rewards/SSW.Rewards/ViewModels/ProfileViewModel.cs, Xamarin/SSW.Rewards/SSW.Rewards/Views/OnBoarding.xaml
This PR adds the completed layout for the v2 dev profiles / people page.
Using placeholder data at the moment, next PR will wire up the viewmodel.
=> 💄 Layout for v2 Dev Profiles

API/SSW.Rewards.Application/Services/UserService.cs, Xamarin/SSW.Rewards/SSW.Rewards.iOS/AppDelegate.cs, Xamarin/SSW.Rewards/SSW.Rewards/App.xaml.cs, Xamarin/SSW.Rewards/SSW.Rewards/AppShell.xaml, Xamarin/SSW.Rewards/SSW.Rewards/Controls/AchievementGrid.xaml, Xamarin/SSW.Rewards/SSW.Rewards/Controls/SkillsBar.xaml.cs, Xamarin/SSW.Rewards/SSW.Rewards/Controls/Snackbar.xaml, Xamarin/SSW.Rewards/SSW.Rewards/Controls/Snackbar.xaml.cs, Xamarin/SSW.Rewards/SSW.Rewards/Converters/IsMeToColorConverter.cs, Xamarin/SSW.Rewards/SSW.Rewards/Helpers/AuthenticatedClientFactory.cs, Xamarin/SSW.Rewards/SSW.Rewards/Pages/LeaderboardPage.xaml, Xamarin/SSW.Rewards/SSW.Rewards/Pages/PeoplePage.xaml, Xamarin/SSW.Rewards/SSW.Rewards/Pages/PeoplePage.xaml.cs, Xamarin/SSW.Rewards/SSW.Rewards/Pages/ProfilePage.xaml, Xamarin/SSW.Rewards/SSW.Rewards/Pages/ProfilePage.xaml.cs, Xamarin/SSW.Rewards/SSW.Rewards/Resolver.cs, Xamarin/SSW.Rewards/SSW.Rewards/Services/IUserService.cs, Xamarin/SSW.Rewards/SSW.Rewards/Services/LeaderService.cs, Xamarin/SSW.Rewards/SSW.Rewards/Services/NotificationRegistrationService.cs, Xamarin/SSW.Rewards/SSW.Rewards/Services/UserService.cs, Xamarin/SSW.Rewards/SSW.Rewards/ViewModels/DevProfilesViewModel.cs, Xamarin/SSW.Rewards/SSW.Rewards/ViewModels/FlyoutHeaderViewModel.cs, Xamarin/SSW.Rewards/SSW.Rewards/ViewModels/LeaderBoardViewModel.cs, Xamarin/SSW.Rewards/SSW.Rewards/ViewModels/LoginPageViewModel.cs, Xamarin/SSW.Rewards/SSW.Rewards/ViewModels/OnBoardingViewModel.cs, Xamarin/SSW.Rewards/SSW.Rewards/ViewModels/ProfileCarouselViewModel.cs, Xamarin/SSW.Rewards/SSW.Rewards/ViewModels/ProfileViewModel.cs, Xamarin/SSW.Rewards/SSW.Rewards/Views/LoginPage.xaml.cs
This completes the dev profiles page, and adds the initial leaderboard page
Also includes some tweaks following interim PO review, and some general housekeeping
Done video: https://youtu.be/HNQVMKeEZFU
=> 💄UI v2: Dev Profiles and Leaderboard

API/SSW.Rewards.Application/Achievements/Command/UpdateAchievement/UpdateAchievementCommand.cs, API/SSW.Rewards.Application/Rewards/Commands/UpdateReward/UpdateRewardCommand.cs, API/SSW.Rewards.Application/Skills/Commands/DeleteSkill/DeleteSkillCommand.cs, API/SSW.Rewards.Application/Skills/Commands/UpsertSkill/UpsertSkillCommand.cs, API/SSW.Rewards.Application/Skills/Queries/GetAdminSkillList/AdminSkill.cs, API/SSW.Rewards.Application/Skills/Queries/GetAdminSkillList/GetAdminSkillListQuery.cs, API/SSW.Rewards.Application/Staff/Commands/DeleteStaffMemberProfile/DeleteStaffMemberProfileCommand.cs, API/SSW.Rewards.Application/Staff/Commands/UpsertStaffMemberProfile/UpsertStaffMemberProfileCommand.cs, API/SSW.Rewards/Controllers/AchievementController.cs, API/SSW.Rewards/Controllers/RewardController.cs, API/SSW.Rewards/Controllers/SkillController.cs, API/SSW.Rewards/Controllers/StaffController.cs, API/SSW.Rewards/wwwroot/api/specification.json, GeneratedClient/ApiClient.g.cs
- Fixes Creating Profiles
- Adds routes:
- Updating Achievements, Rewards 
- Deleting Skills
- create skills
- editing skills
- get skills (with id)
=> ✨Admin Api Updates/Fixes

API/SSW.Rewards.Application/Achievements/Command/DeleteAchievement/DeleteAchievementCommand.cs, API/SSW.Rewards.Application/Achievements/Queries/GetAchievementAdminList/GetAchievementAdminListQuery.cs, API/SSW.Rewards.Application/Achievements/Queries/GetAchievementList/GetAchievementListQuery.cs, API/SSW.Rewards.Domain/Entities/Achievement.cs, API/SSW.Rewards.Persistence/Migrations/20220616230315_AchievementSoftDelete.Designer.cs, API/SSW.Rewards.Persistence/Migrations/20220616230315_AchievementSoftDelete.cs
Solves: https://github.com/SSWConsulting/SSW.Rewards/issues/273
=> 🗃️ Changed DeleteAchievement to soft delete

.github/workflows/xamarin.yml, Xamarin/SSW.Rewards/SSW.Rewards/Services/DevService.cs, Xamarin/SSW.Rewards/SSW.Rewards/Services/LeaderService.cs, Xamarin/SSW.Rewards/SSW.Rewards/Services/RewardService.cs, Xamarin/SSW.Rewards/SSW.Rewards/Services/ScannerService.cs, Xamarin/SSW.Rewards/SSW.Rewards/ViewModels/DevProfilesViewModel.cs, Xamarin/SSW.Rewards/SSW.Rewards/ViewModels/ProfileViewModel.cs, Xamarin/SSW.Rewards/SSW.Rewards/ViewModels/RewardsViewModel.cs
This PR fixes an app crash following an authentication failure (view models trying to process empty or null results returned by services on auth failure)
=> 🐛 Fix auth bug

.github/workflows/xamarin.yml, Xamarin/SSW.Rewards/SSW.Rewards/App.xaml
=> pin to macos-10.15 runners

API/SSW.Rewards.Application/Achievements/Queries/GetAchievementAdminList/AchievementAdminViewModel.cs, API/SSW.Rewards.Application/Achievements/Queries/GetAchievementAdminList/AutoMapperProfile.cs, API/SSW.Rewards.Application/Achievements/Queries/GetAchievementAdminList/GetAchievementAdminListQuery.cs, API/SSW.Rewards/Controllers/AchievementController.cs, GeneratedClient/ApiClient.g.cs
UI PR counterpart: [Pull Request 4021](https://dev.azure.com/ssw/SSW.Rewards/_git/SSW.Rewards.Admin/pullrequest/4021): Add control to show archived achievements
feat:
- Add optional `IncludeArchived` query to return archived achievements
=> Allow admin GET Achievements list to return archived achievement

Xamarin/SSW.Rewards/SSW.Rewards/Services/UserService.cs
- Adds a catch for when a user cancels signing in
- This will now give a LoginFailure error
=> 🥅Catch Signin Cancelled exception

API/SSW.Rewards.Application/Quizzes/Commands/SubmitUserQuiz/QuizResultDto.cs, API/SSW.Rewards.Application/Quizzes/Commands/SubmitUserQuiz/SubmitUserQuizCommand.cs, API/SSW.Rewards.Application/Quizzes/Queries/GetQuizDetailsQuery/GetQuizDetailsQuery.cs, API/SSW.Rewards.Application/Quizzes/Queries/GetQuizDetailsQuery/QuizDetailsDto.cs, API/SSW.Rewards.Application/Quizzes/Queries/GetQuizListForUserQuery/GetQuizListForUserQuery.cs, API/SSW.Rewards.Application/Quizzes/Queries/GetQuizListForUserQuery/QuizDto.cs, API/SSW.Rewards.Domain/Entities/Icons.cs, API/SSW.Rewards/Controllers/QuizzesController.cs, API/SSW.Rewards/wwwroot/api/specification.json, GeneratedClient/ApiClient.g.cs
NOTE: Currently using hard-coded dummy data
=> added endpoints for getting and submitting quizzes.

API/SSW.Rewards.Application/Quizzes/Commands/SubmitUserQuiz/SubmitUserQuizCommand.cs, API/SSW.Rewards/Startup.cs
added missing line in startup that is needed for validators to be used in project.
=> added validator for Quiz submission.

Xamarin/SSW.Rewards/SSW.Rewards.Android/MainActivity.cs, Xamarin/SSW.Rewards/SSW.Rewards.Android/SSW.Rewards.Android.csproj, Xamarin/SSW.Rewards/SSW.Rewards.iOS/AppDelegate.cs, Xamarin/SSW.Rewards/SSW.Rewards.iOS/SSW.Rewards.iOS.csproj, Xamarin/SSW.Rewards/SSW.Rewards/Controls/DevImageView.xaml, Xamarin/SSW.Rewards/SSW.Rewards/Controls/DevImageView.xaml.cs, Xamarin/SSW.Rewards/SSW.Rewards/Pages/PeoplePage.xaml, Xamarin/SSW.Rewards/SSW.Rewards/SSW.Rewards.csproj, Xamarin/SSW.Rewards/SSW.Rewards/Services/DevService.cs
Add loading placeholder
Use ffimageloading greyscale transform for unscanned devs
=> Switch to ffimageloading

Xamarin/SSW.Rewards/SSW.Rewards.Android/Properties/AndroidManifest.xml, Xamarin/SSW.Rewards/SSW.Rewards.iOS/Info.plist, Xamarin/SSW.Rewards/SSW.Rewards/ViewModels/ProfileViewModel.cs
=> Remove Android condition from resetting profile sections on scan

GeneratedClient/ApiClient.g.cs, Xamarin/SSW.Rewards/SSW.Rewards.Android/Properties/AndroidManifest.xml, Xamarin/SSW.Rewards/SSW.Rewards.iOS/Info.plist
This PR fixes an issue that prevents people without a profile picture from being able to log into the app
=> Fix null profilepic

src/SSW.Rewards/PopupPages/LinkSocial.xaml
=> ✨UI | Social media username example

src/SSW.Rewards/Pages/OnBoarding.xaml
=> Added padding row to Onboarding screen for iOS

src/SSW.Rewards/Controls/Snackbar.xaml.cs, src/SSW.Rewards/Pages/ProfilePage.xaml.cs, src/SSW.Rewards/ViewModels/ProfileViewModel.cs
=> Fixed profile crashing on revisit

src/SSW.Rewards/Pages/ProfilePages/MyProfilePage.xaml, src/SSW.Rewards/Pages/ProfilePages/MyProfilePage.xaml.cs
=> Added conditional iOS row programatically

src/SSW.Rewards/Controls/Snackbar.xaml.cs, src/SSW.Rewards/Controls/TabHeader.xaml, src/SSW.Rewards/Controls/TabHeader.xaml.cs, src/SSW.Rewards/SSW.Rewards.Mobile.csproj, src/SSW.Rewards/ViewModels/LeaderBoardViewModel.cs
cc @ulyssesmaclaren
New users opening the app for the first time could feel discouraged by seeing people with huge points values. By defaulting to this week, it makes it feel more competitive.
https://youtu.be/GnpvqEwcUTg
Closes #491
=> Add this week filter

src/Application/Quizzes/Queries/GetQuizListForUser/GetQuizListForUser.cs, src/MobileUI/App.xaml.cs, src/MobileUI/Controls/Snackbar.xaml.cs, src/MobileUI/Pages/QuizDetailsPage.xaml, src/MobileUI/Pages/QuizDetailsPage.xaml.cs, src/MobileUI/Pages/QuizPage.xaml, src/MobileUI/Pages/QuizPage.xaml.cs, src/MobileUI/ViewModels/QuizDetailsViewModel.cs
Changes from #549 were lost when merging all the repos. It looks like when it was brought across again in #567 it got lost along the way and didn't notice.
This restores the changes from #549 that were lost.
No
=> ♻️ Mobile - Restore lost quiz updates

src/MobileUI/Constants.cs, src/MobileUI/Controls/Snackbar.xaml.cs, src/MobileUI/MauiProgram.cs, src/MobileUI/MobileUI.csproj, src/MobileUI/ViewModels/BaseViewModel.cs, src/MobileUI/ViewModels/LoginPageViewModel.cs, src/MobileUI/ViewModels/PeoplePageViewModel.cs, src/MobileUI/ViewModels/ProfileViewModels/ProfileViewModelBase.cs
During a recent huge PR, the mobile build got broken during merge conflict resolution
* Re-register the authentication service
* Remove duplicate code from the base viewmodel (already provided by the Community Toolkit)
* Fix some observable properties
* Update vulnerable packages
NA
=> Fix mobile build

src/AdminUI/AdminUI.csproj, src/Application/SSW.Rewards.Application.csproj, src/Infrastructure/SSW.Rewards.Infrastructure.csproj, src/MobileUI/MobileUI.csproj, src/WebAPI/WebAPI.csproj, tests/Application.IntegrationTests/Application.IntegrationTests.csproj, tests/Application.IntegrationTests/Testing.cs, tests/Application.UnitTests/Application.UnitTests.csproj, tests/Domain.UnitTests/Domain.UnitTests.csproj
As per Adam's email: "⚠️ Important -  SSW Rewards - Nuget - Update 41 packages"
Updates out-of-date NuGet packages with some slight refactoring for library differences.
No
=> ♻️ Update NuGet packages

src/MobileUI/Services/IAuthenticationService.cs
✏️ Forgot to push this commit before merging my last PR...
✏️ Thread lock added GetAccessToken method
✏️ Does ChatGPT count?
=> Added thread lock to GetAccessToken

src/MobileUI/MauiProgram.cs, src/MobileUI/Services/IAuthenticationService.cs, src/MobileUI/Services/UserService.cs, src/MobileUI/ViewModels/FlyoutHeaderViewModel.cs
✏️ Flyout is not updating when values change
✏️ Fixed the service registration lifetimes and moved updating user details out of constructor in flyout.
✏️ I worked with @zacharykeeping
=> Fixed flyout load details at login

.github/workflows/admin-deploy.yml, src/AdminUI/wwwroot/appsettings.staging.json
✏️ Staging admin portal currently uses prod app settings.
Closes #590 
✏️ 
* Add staging appsettings.
* Update deploy bicep to use staging appsettings
✏️ NA
=> Fix staging admin portal

.github/workflows/admin-deploy.yml
✏️ Build of admin portal currently fails for dev
✏️ Changed the environment condition that builds the staging settings from "not production" to "staging"
✏️ NA
=> Fix staging condition in admin portal workflow

src/MobileUI/AppShell.xaml, src/MobileUI/Controls/FlyoutHeader.xaml, src/MobileUI/Controls/Podium.xaml, src/MobileUI/Controls/Podium.xaml.cs, src/MobileUI/Controls/SegmentedControl.xaml.cs, src/MobileUI/Converters/IsMeToColorConverter.cs, src/MobileUI/Converters/StaffToTextConverter.cs, src/MobileUI/Pages/LeaderboardPage.xaml, src/MobileUI/Pages/LeaderboardPage.xaml.cs, src/MobileUI/Resources/Styles/Styles.xaml, src/MobileUI/ViewModels/LeaderViewModel.cs
Updates the leaderboard collection part of #558
Updates the Leaderboard CollectionView to the V3 design.
**Figure: Updated Leaderboard with V3 design**
N/A
=> V3 Leaderboard collection

_docs/Instructions-Compile.md, docker-compose.yml, up.ps1
✏️ @lukecookssw found that the [F5 instructions](https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Instructions-Compile.md) do not work on Windows
✏️ 
* Added a PowerShell script to set up docker environment variables
* Updated docker compose to get the home folder from `.env`
* Updated instructions
✏️ No
=> Make F5 x-plat

src/Application/Common/Interfaces/IQuizGPTService.cs, src/Application/Quizzes/Commands/BeginQuiz/BeginQuizCommand.cs, src/Application/Quizzes/Commands/SubmitAnswerCommand/QuizGPTRequestDto.cs, src/Application/Quizzes/Commands/SubmitAnswerCommand/QuizGPTResponseDto.cs, src/Application/Quizzes/Commands/SubmitAnswerCommand/SubmitAnswerCommand.cs, src/Application/Quizzes/Commands/SubmitAnswerCommand/SubmitAnswerCommandValidator.cs, src/Application/Quizzes/Queries/CheckQuizCompletion/CheckQuizCompletionQuery.cs, src/Application/Quizzes/Queries/GetQuizListForUser/GetQuizListForUser.cs, src/Application/Quizzes/Queries/GetQuizQuestionsBySubmissionId/GetQuizQuestionsBySubmissionIdQuery.cs, src/Application/Quizzes/Queries/GetQuizResults/GetQuizResultsQuery.cs, src/Common/DTOs/Quizzes/BeginQuizDto.cs, src/Common/DTOs/Quizzes/QuestionResultDto.cs, src/Common/DTOs/Quizzes/QuizQuestionDto.cs, src/Common/DTOs/Quizzes/QuizResultDto.cs, src/Common/DTOs/Quizzes/SubmitQuizAnswerDto.cs, src/Common/DTOs/Quizzes/SubmittedAnswerDto.cs, src/Domain/Entities/CompletedQuiz.cs, src/Domain/Entities/QuizQuestion.cs, src/Domain/Entities/SubmittedQuizAnswer.cs, src/Infrastructure/ConfigureServices.cs, src/Infrastructure/Options/GPTServiceOptions.cs, src/Infrastructure/Persistence/Configurations/QuizConfiguration.cs, src/Infrastructure/Persistence/Migrations/20240122031047_AddGPTQuizFields.Designer.cs, src/Infrastructure/Persistence/Migrations/20240122031047_AddGPTQuizFields.cs, src/Infrastructure/Services/QuizGPTService.cs, src/WebAPI/Controllers/QuizzesController.cs, src/WebAPI/appsettings.json
✏️ This was already merged in #601 however we had to revert main due to accidental pushes
✏️ See #601
✏️
=> Lc quizgpt backend

src/Common/DTOs/Leaderboard/LeaderboardUserDto.cs, src/MobileUI/MauiProgram.cs, src/MobileUI/MobileUI.csproj, src/MobileUI/Pages/ProfilePages/OthersProfilePage.xaml, src/MobileUI/Pages/ProfilePages/OthersProfilePage.xaml.cs, src/MobileUI/ViewModels/LeaderBoardViewModel.cs, src/MobileUI/ViewModels/LeaderViewModel.cs, src/MobileUI/ViewModels/ProfileViewModels/OthersProfileViewModel.cs
✏️ Addresses task 2 on [this PBI](https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/609)
✏️ Downgraded PageResolver, it seems like there is [bug there](https://github.com/matt-goldman/Maui.Plugins.PageResolver/issues/26) when `UsePageResolver` is used
✏️ Changed `LeaderViewModel` to inherit from `BaseViewModel`
✏️  No
=> 🐛 Mobile | Stabilisation before release | Fix navigation to OthersPeople profile

src/ApiClient/Services/IAchievementService.cs, src/WebAPI/Controllers/AchievementController.cs, src/WebAPI/Controllers/RewardController.cs
Fixes part of #621 - "QR code scanner scans codes, but always shows "Something went wrong here" animation" and "QR code scanner doesn't pick up SSW employees QR codes"
Fixes an issues where the Claim endpoint never gets hit.
No
=> 🐛 Mobile - Fix QR code scanning broken

src/WebAPI/appsettings.json
Updated appSettings to have correct GPT URI.
✏️ 
✏️
=> added prod GPT URI to appSettings.json

infra/modules/webapp.bicep, src/WebAPI/appsettings.json
Moved URL to pipeline so it doesn't break if someone changes the value in `appsettings.json`
GPT URI is being replaced as part of the pipeline.
✏️
=> added gpt uri to bicep template

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
✏️ New release
✏️ Version number, build number, info.plist
✏️ No
=> ✨ Bump Android and iOS versions; update info.plist

infra/modules/webapp.bicep
=> removed trailing semicolon

src/MobileUI/ViewModels/LeaderViewModel.cs
Closes #638
Fixes This Week not working in the leaderboard due to the value being unmapped.
**Figure: This Week now showing correctly**
No
=> 🐛 Mobile | Fix This Week not working in leaderboard

src/MobileUI/AppShell.xaml, src/MobileUI/Pages/EarnDetailsPage.xaml
✏️ Email from Adam: Rewards - 2nd question 
✏️  Added prefix to the Question and Answer in Quizzes
✏️ @zacharykeeping
=> Add Prefix to Questions and Answers

src/ApiClient/Services/IUserService.cs, src/Infrastructure/Services/ProfilePicStorageProvider.cs, src/MobileUI/Controls/ProfileStats.xaml, src/MobileUI/Services/IUserService.cs, src/MobileUI/Services/UserService.cs, src/MobileUI/ViewModels/CameraPageViewModel.cs, src/MobileUI/ViewModels/ProfileViewModels/MyProfileViewModel.cs, src/MobileUI/ViewModels/ProfileViewModels/OthersProfileViewModel.cs, src/MobileUI/ViewModels/ProfileViewModels/ProfileViewModelBase.cs, src/WebAPI/Controllers/UserController.cs
Part of #621
Closes #650 
Fixes an issue where the camera button never shows on a user's profile and thus can't upload a new avatar.
@tkapa
=> 🐛 Mobile | Fix camera button not showing on profile

src/MobileUI/Controls/ProfileStats.xaml, src/MobileUI/Pages/ProfilePages/MyProfilePage.xaml, src/MobileUI/Pages/ProfilePages/MyProfilePage.xaml.cs, src/MobileUI/Pages/ProfilePages/OthersProfilePage.xaml, src/MobileUI/Resources/Styles/Colors.xaml, src/MobileUI/ViewModels/ProfileViewModels/MyProfileViewModel.cs, src/MobileUI/ViewModels/ProfileViewModels/OthersProfileViewModel.cs, src/MobileUI/ViewModels/ProfileViewModels/ProfileViewModelBase.cs
✏️ Figma
✏️ updated the Profile page to partially migrate to the V3 Design
✏️ @zacharykeeping
=> 💄 Mobile UI - V3 Profile - Partial Implementation

src/WebAPI/Controllers/RewardController.cs
Bug report from Camilla
Fixed an issue where our api endpoint for reward redemption was not being hit properly.
Yes with @tkapa
=> 🐛 Mobile | Fix rewards api endpoint

src/ApiClient/Services/IRewardService.cs, src/WebAPI/Controllers/RewardController.cs
Bug report from Camilla
Fix how our endpoint is hit for rewards redemption
yes with @tkapa
=> 🐛 Mobile | Fix rewards redemption not working

src/WebAPI/Controllers/StaffController.cs
✏️ Test request from Camilla
✏️ Fixed a bug where Title wasn't being passed to the Command
✏️ No
=> Add Title to Upsert Command

src/MobileUI/Controls/ProfileStats.xaml, src/MobileUI/Pages/ProfilePages/MyProfilePage.xaml, src/MobileUI/Pages/ProfilePages/OthersProfilePage.xaml
Part of #613 
Updates the spacing and design of the table section of the V3 profile
@tkapa
=> 🐛 Mobile | Fix layout on V3 profile page

.github/workflows/admin-main.yml
✏️  We have a lot of Workflows in progress due to PRs being merged.
✏️ 
✏️ @zacharykeeping
=> Stop Admin Deploy on Push to Main

src/MobileUI/Pages/ScanPage.xaml
Email from @adamcogan: "Rewards tab - Scan - double the instructions text"
A background was added to this text for better readability and the font has been increased.
**Figure: Updated text in scanner**
With @tkapa
=> ♻️ Mobile | Improve text readability on scanner

src/MobileUI/AppShell.xaml, src/MobileUI/Controls/FlyoutHeader.xaml
✏️ Email from @adamcogan RE: SSW Rewards - iOS iPad UX issues
✏️  Update Flyout font sizes to reduce text cut off in the app for iOS and iPad
✏️ @zacharykeeping
=> Update Font Sizes

src/MobileUI/AppShell.xaml, src/MobileUI/Controls/FlyoutHeader.xaml
Updating Fly out spacing as per my conversation with Jayden
=> Address flyout cutoffs

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
New version released
Bumped the version numbers in the code
No
=> Bump version number

.github/workflows/admin-main.yml
✏️ Issue with syntax on a workflow
✏️ 
✏️
=> Fix failing workflows

.github/workflows/admin-main.yml, src/Application/Users/Commands/RegisterUser/RegisterUserCommand.cs
✏️ I spotted an issue where Users weren't being created with a date time
✏️ 
✏️
=> 🐛 Fix user creation date

src/MobileUI/AppShell.xaml, src/MobileUI/Controls/FlyoutHeader.xaml, src/MobileUI/Controls/ProfileStats.xaml, src/MobileUI/Pages/ScanPage.xaml
Part of #680 
Implements UI improvements based on feedback from NDC.
**Figure: Leaderboard rank is now more obvious, QR code has "scan me" text, and bottom buttons are further spaced out**
**Figure: Scanner text is now simpler and larger**
No
=> ♻️ Mobile | Implement UI improvements from feedback

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
promoted release
bumped version numbers
no
=> Bump version numbers

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
=> Bump versions

.github/workflows/mobile-main.yml
✏️ GitHub Actions (mobile) not working
✏️ Changed dependency
✏️ N/A
=> Update iOS deploy dependency

.github/workflows/ios-build.yml, src/MobileUI/Platforms/iOS/Info.plist
=> Actions | Remove certificate import

.github/workflows/ios-build.yml
=> Update ios build

src/MobileUI/Controls/Podium.xaml.cs, src/MobileUI/Pages/LeaderboardPage.xaml, src/MobileUI/Pages/LeaderboardPage.xaml.cs
✏️ Only half of the page is scrollable
✏️ The leaders were placed in a `CollectionView.Header`
✏️ No
=> Mobile | Make Leaderboard page fully scrollable

.github/workflows/ios-build.yml
=> Use import-codesign-certs job from Apple

src/AdminUI/Pages/Achievements.razor, src/AdminUI/Pages/Leaderboard.razor, src/AdminUI/Pages/NewUsers.razor, src/AdminUI/Pages/Notifications.razor, src/AdminUI/Pages/PrizeDraw.razor, src/AdminUI/Pages/Profiles.razor, src/AdminUI/Pages/Quizzes.razor, src/AdminUI/Pages/Rewards.razor, src/AdminUI/Pages/Skills.razor, src/AdminUI/Shared/MainLayout.razor, src/AdminUI/Shared/NavMenu.razor
✏️ We currently have some pages that restrict functionality only to Admin users. However, all pages are visible to users regardless of their roles, even if they aren't Staff or Admin!
✏️ Adds Roles to most of the Authorization tags in `AdminUI.csproj`
Updates the NavMenu to hide items from non-Admin and non-Staff users.
✏️
=> ✨ Admin | RBAC for Staff and Admin Users

src/AdminUI/Components/Dialogs/Rewards/RewardsEditDialog.razor, src/Infrastructure/Services/RewardPicStorageProvider.cs
Prepping the Rewards portal for In-App redeeming of Rewards
✏️ Fixes an issue with the `RewardStorageProvider` 
Updates the `RewardEditDialog` to include a view of the existing reward image and allow uploading of the image.
✏️ No
=> 🐛 Admin | Rewards images

_docs/Instructions-Compile.md
✏️ Change in how we use Provisioning Profiles and certificates
✏️ F5 readme
✏️ No
=> Mobile | Update F5

src/ApiClient/Services/IUserService.cs, src/Application/Staff/Queries/GetStaffMemberProfile/GetStaffMemberProfileQuery.cs, src/MobileUI/Controls/ProfileActivity.xaml, src/MobileUI/Controls/ProfileActivityItem.xaml, src/MobileUI/Controls/ProfileStats.xaml, src/MobileUI/Converters/LevelToStarsConverter.cs, src/MobileUI/Pages/ProfilePages/OthersProfilePage.xaml, src/MobileUI/Services/DevService.cs, src/MobileUI/Services/IDevService.cs, src/MobileUI/ViewModels/ProfileViewModels/MyProfileViewModel.cs, src/MobileUI/ViewModels/ProfileViewModels/OthersProfileViewModel.cs, src/MobileUI/ViewModels/ProfileViewModels/ProfileViewModelBase.cs
Part of #613 
Adds the Skill Set section to SSW profile pages (with placeholder icons for the time being). This takes the [up to] top 3 skills for a user to display on the page.
Also tweaks the design for better consistency and to better match the V3 mockups.
**Figure: Updated profile page with Skill Set section**
No
=> ♻️ Mobile | V3 Profile part 3

src/MobileUI/App.xaml, src/MobileUI/AppShell.xaml, src/MobileUI/AppShell.xaml.cs, src/MobileUI/Helpers/Icon.cs, src/MobileUI/MauiProgram.cs, src/MobileUI/Messages/TopBarAvatarMessage.cs, src/MobileUI/MobileUI.csproj, src/MobileUI/Pages/EarnDetailsPage.xaml, src/MobileUI/Pages/EarnPage.xaml, src/MobileUI/Pages/LeaderboardPage.xaml, src/MobileUI/Pages/PeoplePage.xaml, src/MobileUI/Pages/ProfilePages/MyProfilePage.xaml, src/MobileUI/Pages/ProfilePages/OthersProfilePage.xaml, src/MobileUI/Pages/ScanPage.xaml, src/MobileUI/Pages/ScanPage.xaml.cs, src/MobileUI/Resources/Styles/Templates.xaml, src/MobileUI/ViewModels/EarnDetailsViewModel.cs, src/MobileUI/ViewModels/FlyoutHeaderViewModel.cs, src/MobileUI/ViewModels/TopBarViewModel.cs
✏️ Closes #612 
✏️ Top bar was added as per the v3 UI (minus the search bar - to be implemented as part of #561)
✏️ NA
=> Add v3 topbar

src/MobileUI/ViewModels/TopBarViewModel.cs
✏️ There was a significant bug in #722 
✏️ Changed from:
```csharp
private void SetDoneButton()
{
SetDoneButton();
}
```
(lol)
to:
```csharp
private void SetDoneButton()
{
ShowDone = true;
ShowBack = false;
ShowAvatar = false;
}
```
✏️ I worked with @Anton-Polkanov  and @tkapa
=> Fix circular method in TopBarViewModel

.github/ISSUE_TEMPLATE/ssw-rewards--sprint-forecast-template.md, .github/ISSUE_TEMPLATE/ssw-rewards--sprint-review-template.md
Easy Sprint Email Creation
Update Sprint Email Templates
✏️ no
=> 📄 Sprint Templates | Update Sprint Issue Templates

src/MobileUI/Pages/ScanPage.xaml, src/MobileUI/Pages/ScanPage.xaml.cs, src/MobileUI/Resources/Styles/Styles.xaml, src/MobileUI/Resources/Styles/Templates.xaml, src/MobileUI/ViewModels/ScanResultViewModel.cs, src/MobileUI/ViewModels/TopBarViewModel.cs
✏️ Visual bug on iOS raised by @zacharykeeping 
This is due to an open bug in .NET MAUI. See:
https://github.com/dotnet/maui/issues/18948
https://github.com/dotnet/maui/issues/17550
✏️ A global style was used to hide the navigation bar in `Page` derived types. Also the top bar is shifted upward on iOS to close a gap.
✏️  NA
=> Hide navigation bar on iOS and shift topbar upwards.

src/MobileUI/Controls/ProfileStats.xaml, src/MobileUI/MauiProgram.cs, src/MobileUI/Pages/ProfilePages/OthersProfilePage.xaml, src/MobileUI/ViewModels/LeaderBoardViewModel.cs
✏️ #738 
✏️ Used a base class in `x:DataType`
✏️ No
=> 🐛 Mobile | Profile issue

src/MobileUI/Pages/PeoplePage.xaml, src/MobileUI/Pages/ScanPage.xaml, src/MobileUI/Services/DevService.cs, src/MobileUI/Services/ScannerService.cs, src/MobileUI/ViewModels/PeoplePageViewModel.cs, src/MobileUI/ViewModels/ScanResultViewModel.cs
✏️ #655 
✏️ Remove multiple calls of WeakReferenceMessenger which caused duplicate data fetches;
Clear `Profiles` observable collection before adding data;
If we need to re-fetch data for the People page, do it only when users navigates to it.
✏️ No
=> 🐛 Mobile | People page fix

src/MobileUI/AppShell.xaml, src/MobileUI/Helpers/ObservableRangeCollection.cs, src/MobileUI/Pages/LeaderboardPage.xaml, src/MobileUI/Pages/PeoplePage.xaml, src/MobileUI/Pages/ProfilePages/MyProfilePage.xaml, src/MobileUI/Pages/ProfilePages/OthersProfilePage.xaml, src/MobileUI/Pages/ScanPage.xaml, src/MobileUI/Platforms/Android/MainActivity.cs, src/MobileUI/Resources/Styles/Styles.xaml, src/MobileUI/Resources/Styles/Templates.xaml, src/MobileUI/ViewModels/PeoplePageViewModel.cs
✏️ Minor issues in different parts of the app
✏️ Updated status bar background color so that it matches with the TopBar
Reduced the size of the Back arrow in the TopBar (displayed in quizzes)
Added `ObservableRangeCollection` which does not fire PropertyChanged event on every modification. Used it on the PeoplePage for now.
✏️ No
=> ♻️ Mobile | Add ObservableRangeCollection

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
✏️ Release
✏️ App version
✏️ No
=> ✨ Mobile | Bump Android & iOS versions

src/MobileUI/Constants.cs
✏️  Incorrect app id. As a result, dev and production logs in AppCenter are mixed up
✏️  App id for iOS
✏️ No
=> ♻️ Mobile | Change AppCenter app id

src/MobileUI/Helpers/AuthBrowser.cs, src/MobileUI/Services/IAuthenticationService.cs
✏️ #731 
✏️  Used TryGetValue with an Empty string as a default. Also added try-catch with logging.
✏️ Yes, with @matt-goldman
=> 🐛Mobile | Fix ParseAuthenticationResult() and add logging

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
=> ✨ Mobile | Bump versions

src/MobileUI/Pages/NetworkPage.xaml
✏️ Incorrect UI on the Android page
✏️ Removed fixed sizes and set different Sizing strategy for iOS and Android.
✏️ No
| <img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/27bcc348-640e-4fc2-aa59-18b828023d5f" width=200/> | <img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/e990c1c0-e3a2-44ff-bcf1-91e59fd4563d"  width=200/> |
|-------|--------|
| Figure: ❌ Android - Before | Figure: ✅ Android - After |
=> 🐛 Mobile | Fix Network page on Android

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
=> ✨ Mobile | Version bump

src/AdminUI/Pages/Quizzes.razor
Closes #660 
Hides archived quizzes in the UI by default.
=> ✨ Admin | Hide or Show Archived Quizzes

src/AdminUI/Components/Dialogs/Quizzes/QuizQuestionDialog.razor, src/AdminUI/Components/QuizDetails.razor, src/Application/Quizzes/Commands/AdminUpdateQuiz/AdminUpdateQuiz.cs, src/Common/DTOs/Quizzes/QuizQuestionEditDto.cs
Closes #659 
Closes #651 
Adds the ability to Delete quiz questions to the Admin UI.
Note, I've created a PBI to investigate data loss issues, however, I'm unsure if the effort to implement this is worth the effort. https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/773
✏️ no
=> ✨ Admin/API | Delete quiz questions

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/docs.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/refactor.md
✏️ I got fed up of seeing
> - [x] Meets definition of done {{ LINK }}
in issues. And tbh, I wasn't updating the link either, just deleting the placeholder.
✏️ Added the actual URL to the templates
✏️ Nope
=> Add DOD link to templates

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
=> ✨ Mobile | Bump

infra/main.bicep, infra/modules/maps.bicep, infra/modules/webapp.bicep
✏️ #791 
✏️ Created a bicep script which would create an Azure Maps account and save the key to key vault
✏️ No
=> 🐛 Mobile | Add bicep script for Azure Maps

src/AdminUI/AdminUI.csproj, src/AdminUI/Components/Dialogs/Rewards/RewardsEditDialog.razor, src/Application/Rewards/Commands/UpdateReward/UpdateRewardCommand.cs, src/Common/DTOs/Rewards/RewardEditDto.cs, src/WebAPI/Controllers/RewardController.cs
=> ✨ Admin | Add Deletion of Rewards Images

infra/main.bicep, infra/modules/maps.bicep
✏️ #791 
✏️ Changed region for Maps as they are not available in australia
✏️ No
=> 🐛 Mobile | Update bicep script for Azure Maps

src/MobileUI/Services/IAuthenticationService.cs
✏️ #731 
✏️ Added logs to figure out where the `LoginFailure` is coming from
✏️ No
=> ♻️ Mobile | Add extra logging

src/MobileUI/Models/ApiStatus.cs, src/MobileUI/Services/IAuthenticationService.cs, src/MobileUI/Services/IUserService.cs, src/MobileUI/Services/UserService.cs, src/MobileUI/ViewModels/LoginPageViewModel.cs
✏️ #731
✏️ Removed duplicate property `HasCachedAccount` from the `UserService`
Removed code which reads data from `IdentityToken`
Fixed error which popups up when the user closes the browser without logging-in.
✏️ No
=> ♻️ Mobile | Cleanup LoginViewModel and Auth service

src/AdminUI/Components/Dialogs/Users/EditUserRoles.razor, src/AdminUI/Pages/Users.razor, src/AdminUI/Shared/NavMenu.razor, src/ApiClient/ConfigureServices.cs, src/ApiClient/Services/IRoleService.cs, src/ApiClient/Services/IUserAdminService.cs, src/Application/Common/Interfaces/IRolesService.cs, src/Application/Common/Interfaces/IUserService.cs, src/Application/Roles/Queries/GetRoles/GetRolesQuery.cs, src/Application/Roles/Queries/GetRoles/Mapping.cs, src/Application/Services/UserService.cs, src/Application/Users/Commands/AdminUpdateUserRoles/AdminUpdateUserRolesCommand.cs, src/Application/Users/Common/Mapping.cs, src/Application/Users/Queries/GetUsers/GetUsersQuery.cs, src/Application/Users/Queries/GetUsers/Mapping.cs, src/Common/DTOs/Roles/RoleDto.cs, src/Common/DTOs/Users/UserDto.cs, src/Common/DTOs/Users/UserRoleDto.cs, src/Common/DTOs/Users/UsersViewModel.cs, src/WebAPI/Controllers/RoleController.cs, src/WebAPI/Controllers/UserController.cs
Closes #509
Adds a new Users section with the ability to modify roles against each user.
**Figure: List of all users with edit button against roles**
**Figure: Roles can be modified**
**Figure: Multiple roles can be selected**
No
=> ✨ Admin | User role management

src/Application/ActivityFeed/Queries/GetActivitiesQuery.cs
Closes #836 
Updates the API for the friends feed to not include the current user's activity. Also cleans up the code slightly.
No
=> 🐛 Mobile | Don't show current user's activity in Friends feed

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
=> ✨ Mobile | Version bump v3.0.16

src/MobileUI/AppShell.xaml, src/MobileUI/AppShell.xaml.cs, src/MobileUI/Controls/FlyoutHeader.xaml, src/MobileUI/MobileUI.csproj, src/MobileUI/Pages/SettingsPage.xaml, src/MobileUI/Pages/SettingsPage.xaml.cs, src/MobileUI/PopupPages/OnBoardingPage.xaml.cs, src/MobileUI/Resources/Styles/Templates.xaml, src/MobileUI/ViewModels/OnBoardingViewModel.cs, src/MobileUI/ViewModels/SettingsViewModel.cs
Closes #582 
Simplifies the flyout options by moving them to a new Settings page.
**Figure: Simplified flyout with new Settings option**
**Figure: New Settings page**
No
=> ✨ Mobile | Implement Settings page and tweak flyout

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
=> ✨ Mobile | Disable auto backup and bump to v3.0.18

src/MobileUI/Pages/SettingsPage.xaml, src/MobileUI/Pages/SettingsPage.xaml.cs, src/MobileUI/PopupPages/AboutSSW.xaml, src/MobileUI/PopupPages/OnBoardingPage.xaml, src/MobileUI/Resources/Styles/Templates.xaml, src/MobileUI/ViewModels/TopBarViewModel.cs
Part of #856
1. Decreases size of X on About modal
2. Removes Get Started button from intro
3. Hide scanner icon when on the Settings page
No
=> 🐛 Mobile | Settings fixes

.github/workflows/android-build.yml
=> 🐛 Pipeline | Use bash

src/ApiClient/Services/IUserService.cs, src/Application/Users/Commands/UpsertUserSocialMediaId/UpsertUserSocialMediaIdCommand.cs, src/Common/DTOs/Users/UserSocialMediaIdDto.cs, src/MobileUI/Controls/Snackbar.xaml, src/MobileUI/MauiProgram.cs, src/MobileUI/MobileUI.csproj, src/MobileUI/Pages/SettingsPage.xaml, src/MobileUI/PopupPages/AboutSSW.xaml, src/MobileUI/PopupPages/AboutSSW.xaml.cs, src/MobileUI/PopupPages/AddLinkedInPage.xaml, src/MobileUI/PopupPages/AddLinkedInPage.xaml.cs, src/MobileUI/PopupPages/OnBoardingPage.xaml, src/MobileUI/Services/IUserService.cs, src/MobileUI/Services/UserService.cs, src/MobileUI/ViewModels/AddLinkedInViewModel.cs, src/MobileUI/ViewModels/SettingsViewModel.cs, src/WebAPI/Controllers/UserController.cs
✏️ #799 
✏️  There is a new item in the Settings which allows to add a LinkedIn profile.
We do basic validation to make sure the URL is legit.
Also update Maui.Controls to the latest .NET 8 version to fix UI bugs.
✏️ No
=> ✨ Mobile | Add LinkedIn profile

src/MobileUI/Pages/LeaderboardPage.xaml, src/MobileUI/ViewModels/LeaderBoardViewModel.cs
✏️ #881 
✏️ Added the button
✏️ No
=> ✨ Mobile | Add ScrollToMe button

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
=> ✨ Mobile | Bump to v3.0.19

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
=> ✨ Mobile | Bump to v3.0.20

src/AdminUI/Pages/DetailedProfile.razor
Closes #515 
Sets individual profile pages to only load when the Admin role is present.
No
=> 🐛 Admin | Set admin role on profile page

src/MobileUI/Services/UserService.cs, src/MobileUI/ViewModels/LeaderBoardViewModel.cs, src/MobileUI/ViewModels/LeaderViewModel.cs, src/MobileUI/ViewModels/ProfileViewModels/ProfileViewModelBase.cs
Closes #901 
The UpdateMyAllTimeRank() method wasn't correctly setting the all time rank and doing an unnecessary sort. This fixes that and also updates the default rank to 0 so it won't sometimes show the max int on load.
No
=> 🐛 Mobile | Fix rank changing in flyout

src/MobileUI/PopupPages/ProfilePicturePage.xaml, src/MobileUI/ViewModels/ProfilePictureViewModel.cs
Part of #900
Adds error handling on photo upload so the app shouldn't crash if there's an issue uploading the image.
No.
=> 🐛 Mobile | Add error handling to image upload

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
=> ♻️ Mobile | Bump to version 3.0.21

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
=> ♻️ Mobile | Bump to v3.0.22

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
=> ✨ Mobile | Bump to v3.0.23

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
=> ✨ Mobile | Bump to v3.0.24

src/MobileUI/Controls/ListItem.xaml, src/MobileUI/Pages/EarnPage.xaml, src/MobileUI/Pages/RedeemPage.xaml
Previous discussion with Anton.
Small change to update BindableLayout to CollectionView on the Earn and Redeem pages.
No.
=> ♻️ Mobile | Move to CollectionView on EarnPage and RedeemPage

src/MobileUI/MauiProgram.cs, src/MobileUI/Platforms/Android/Renderers/CustomTableViewRenderer.cs, src/MobileUI/Platforms/iOS/Renderers/CustomTableViewRenderer.cs
Closes #856 
Added shimmed renderer
No
**Figure: Dividers for headers and cells are transparent**
=> 🐛 Mobile | Settings page issues

src/AdminUI/Pages/PrizeDraw.razor
Closes #921 
Hides the Claim Prize button for the time being as this functionality was never completed.
No
=> 🐛 Admin | Hide Claim Prize button

.github/workflows/ios-build.yml, src/MobileUI/MauiProgram.cs, src/MobileUI/MobileUI.csproj, src/MobileUI/Platforms/iOS/GoogleService-Info.plist
Part of #500 
Installs and sets up Google Analytics in the project.
No
=> ✨ Mobile | Install Google Analytics

.github/workflows/admin-deploy.yml, .github/workflows/api-az-deploy.yml, .github/workflows/az-deploy.yml
Failing admin deploy
Updates usages of azure/login in the GitHub Actions to v2 to fix this issue: https://github.com/Azure/login/issues/447
No
=> Update azure/login to v2

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
=> Bump to version v3.0.26

src/MobileUI/Features/Scanner/ScanPage.xaml.cs
cc: @zacharykeeping 
1. Open the scanner
2. Close it
3. Open the scanner again
Result: the camera freezes (see the video below)
✏️ Removed a line which was disconnecting a `Handler`.
✏️ No
https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/71269390-ce53-4adf-80b3-03633b0b752e
=> 🐛 Mobile | Reverting a change from PR #912, issue #896

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
=> ✨ Mobile | Bump to v3.0.27

src/MobileUI/Features/Redeem/RedeemRewardPage.xaml
Closes #962 
Makes it clearer that only Australian addresses are accepted.
**Figure: Updates button to show Australia only**
**Figure: Updates text to show Australia only**
**Figure: Shows Australia in the address**
**Figure: Shows a new readonly field with Australia as the country**
No.
=> ♻️ Mobile | Limit to Australian addresses

src/Application/Common/Interfaces/IEmailService.cs, src/Application/Users/Commands/AdminDeleteProfile/AdminDeleteProfileCommand.cs, src/Application/Users/Commands/Common/DeleteProfileEmail.cs, src/Infrastructure/SSW.Rewards.Infrastructure.csproj, src/Infrastructure/Services/EmailService.cs, src/Infrastructure/Services/EmailTemplates/DigitalReward.cshtml, src/Infrastructure/Services/EmailTemplates/FormCompletionCreateAccount.cshtml, src/Infrastructure/Services/EmailTemplates/FormCompletionPointsReceived.cshtml, src/Infrastructure/Services/EmailTemplates/PhysicalReward.cshtml, src/Infrastructure/Services/EmailTemplates/ProfileDeletionConfirmation.cshtml, src/Infrastructure/Services/EmailTemplates/ProfileDeletionRequest.cshtml
Work on new emails
Cleans up the email service by updating it to use template files and moves all existing emails to this format
No
=> ♻️ Move to template files for emails

src/Infrastructure/ConfigureServices.cs, src/MobileUI/Features/Quiz/QuizDetailsViewModel.cs
#867 
Tweaks the quiz completion check delay to check more frequently.
Tweaks the HangFire options with more optimal defaults
No
=> ♻️ Mobile | Quiz improvements

.github/workflows/admin-deploy.yml, .github/workflows/admin-main.yml
Closes #669
Updates the admin deployment workflow to purge the CDN after deployment.
No
=> ♻️ Update admin workflow to purge CDN

src/MobileUI/Common/ImageHelpers.cs, src/MobileUI/Features/Leaderboard/LeaderboardPage.xaml, src/MobileUI/Features/Redeem/RedeemRewardPage.xaml, src/MobileUI/Features/Redeem/RedeemRewardViewModel.cs, src/MobileUI/Features/Scanner/QrCodePage.xaml, src/MobileUI/Features/Scanner/QrCodeViewModel.cs, src/MobileUI/Features/Scanner/ScanPage.xaml, src/MobileUI/Features/Scanner/ScanPage.xaml.cs, src/MobileUI/MauiProgram.cs, src/MobileUI/MobileUI.csproj
Closes #948
Closes #896
Moves the scanning library to BarcodeScanning.Native.Maui which is more up-to-date, has improved scanning based on native APIs, and has better zoom control for handling different lenses.
This means scanning on newer iPhones will be handled better out of the box, but I've also added zoom buttons to allow the user to zoom in and out if needed (which will also switch between lenses at different zoom levels).
This new library also fixes #896 where the camera indicator never turns off after the scanner is closed.
Also moves to QRCoder for generating QR codes as we were also using the ZXing.Net.Maui.Controls library for this.
**Figure: New zoom buttons**
> 3. Did …
=> ♻️ Mobile | Improve QR code scanning

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
=> Bump to v3.0.29

src/Application/Achievements/Command/ClaimFormCompletedAchievement/ClaimFormCompletedAchievementCommand.cs, src/Application/Common/Models/FormCompletionCreateAccountEmail.cs, src/Application/Common/Models/FormCompletionPointsReceivedEmail.cs, src/Infrastructure/Services/EmailService.cs, src/Infrastructure/Services/EmailTemplates/FormCompletionCreateAccount.cshtml, src/Infrastructure/Services/EmailTemplates/FormCompletionPointsReceived.cshtml
#964
Updates the email templates after Google Form submissions using the new designs from Betty.
**Figure: Email Template – New User**
**Figure: Email Template – Existing User**
No
=> ♻️ API | Update email templates

src/Application/Services/UserService.cs
Issues with Josh B. signing in
Only allows filtering through EXISTING Profiles for the user's QR Code.
✏️
=> Update GetStaffQRCode to exclude archived members

.github/workflows/api-main.yml, infra/main.bicep, infra/modules/law.bicep, infra/modules/webapp.bicep
Classic Application Insights migration:
https://portal.azure.com/#@sswcom.onmicrosoft.com/resource/subscriptions/b8b18dcf-d83b-47e2-9886-00c2e983629e/resourceGroups/SSW.Rewards.Prod/providers/Microsoft.Insights/components/ai-sswrewards-prod/overview
- The Bicep has been tested on staging and Log Analytic Workspace has been deployed successfully:
https://portal.azure.com/#@sswcom.onmicrosoft.com/resource/subscriptions/b8b18dcf-d83b-47e2-9886-00c2e983629e/resourceGroups/SSW.Rewards.Staging/providers/microsoft.insights/components/ai-sswrewards-staging/overview
https://portal.azure.com/#@sswcom.onmicrosoft.com/resource/subscriptions/b8b18dcf-d83b-47e2-9886-00c2e983629e/resourceGroups/SSW.Rewards.Staging/over …
=> Migrate Classic Application Insights: Update Bicep to Add Log Analytics Workspace

src/Application/Rewards/Queries/GetRewardList/GetRewardList.cs
✏️ Closes #982 
✏️ Forcefully sorts all rewards containing Tina to the top of the list.
This should only be done for CDF
✏️
=> Sort Tina rewards to the top of the list

.github/workflows/ci.yml, .github/workflows/ios-build.yml
Failing build
Undo rollback on non-Android builds to fix failing workflow
No
=> Fix rollback

src/MobileUI/Features/Redeem/RedeemRewardViewModel.cs
Testing
Small bug fix to fix an issue where the brightness can change unexpectedly if the popup is opened and closed without showing the QR code.
No
=> 🐛 Mobile | Brightness fix

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
=> Bump to 3.0.31

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
=> Bump to v3.0.32

src/MobileUI/Controls/SocialMedia.xaml, src/MobileUI/Features/Activity/ActivityPageViewModel.cs, src/MobileUI/Features/GitHub/AddGitHubPage.xaml, src/MobileUI/Features/GitHub/AddGitHubPage.xaml.cs, src/MobileUI/Features/GitHub/AddGitHubViewModel.cs, src/MobileUI/Features/Profile/ProfileViewModelBase.cs, src/MobileUI/Features/Settings/SettingsPage.xaml, src/MobileUI/Features/Settings/SettingsViewModel.cs, src/MobileUI/Features/Twitter/AddTwitterPage.xaml, src/MobileUI/Features/Twitter/AddTwitterPage.xaml.cs, src/MobileUI/Features/Twitter/AddTwitterViewModel.cs, src/MobileUI/Services/UserService.cs
Closes #1005 
Closes #1006 
- Hooks up the GitHub and Twitter buttons on profiles similar to LinkedIn
- Hides social media buttons on other users' profiles if they don't exist
Note: a lot of this code should probably be cleaned up or made generic. We also use achievements here that should either be renamed properly in the database or have new ones created (keeping in mind that some users already have these achievements/have linked profiles)
No
=> ✨ Mobile | Hook up GitHub and Twitter profiles

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
=> Bump to v3.0.33

src/Application/Common/Extensions/UserExtensions.cs, src/Application/Services/UserService.cs, src/Application/System/Commands/SeedUserAchievements/SeedUserAchievementsCommand.cs, src/Application/Users/Commands/RegisterUser/RegisterUserCommand.cs, src/Application/Users/Queries/GetCurrentUser/GetCurrentUserQuery.cs, src/Application/Users/Queries/GetCurrentUser/Mapping.cs, src/Domain/Entities/User.cs, src/Infrastructure/Persistence/Migrations/20240830002340_AddUserQRCodes.Designer.cs, src/Infrastructure/Persistence/Migrations/20240830002340_AddUserQRCodes.cs, src/MobileUI/Features/App.xaml.cs, src/MobileUI/Features/AppShell.xaml, src/MobileUI/Features/AppShell.xaml.cs, src/MobileUI/Features/Login/LoginPageViewModel.cs, src/MobileUI/MauiProgram.cs, src/WebAPI/Controllers/SeedController.cs
✏️ #739 
✏️ 
* Added achievement for new users
* Added admin endpoint to seed achievements for all users
* Removed staff requirement for QR codes in mobile app
✏️
=> 739 scan all users

src/Application/ActivityFeed/Queries/GetActivitiesQuery.cs, src/Application/Network/Queries/GetNetworkProfileList/GetNetworkProfileListQuery.cs, src/Common/DTOs/Network/NetworkProfileDto.cs, src/MobileUI/Common/ObservableRangeCollection.cs, src/MobileUI/Features/Network/NetworkPageViewModel.cs
=> ✨ Mobile | Update network page with followers and following

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
=> Increment mobile versions

src/Application/ActivityFeed/Queries/GetActivitiesQuery.cs, src/Application/Network/Queries/GetNetworkProfileList/GetNetworkProfileListQuery.cs
=> Fixed network and activity queries

_docs/Definition-of-Done.md
Adam's email (subject "Rewards - definition of done")
Adds a link to our Definition of Done rule to the bottom of our Definition of Done.
No
=> ♻️ Docs | Add link to rule on Definition of Done

src/Application/Achievements/Command/PostAchievement/PostAchievementCommand.cs, src/Common/DTOs/Achievements/AchievementDto.cs, src/MobileUI/Features/Scanner/ScanResponseViewModel.cs, src/MobileUI/Features/Scanner/ScanResultViewModel.cs, src/MobileUI/Features/Scanner/ScanViewModel.cs, src/MobileUI/Services/ScannerService.cs
Closes #1042 
Open's a user's profile when scanning their QR code.
No
=> ✨ Mobile | Open profile when scanning user

.github/ISSUE_TEMPLATE/ssw-rewards--sprint-forecast-template.md, .github/ISSUE_TEMPLATE/ssw-rewards--sprint-review-template.md
Conversation with Adam
Updates the Sprint templates with better formatting, more emojis and fixed links.
No
=> ♻️ GitHub | Update Sprint templates

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
=> Bump to v3.0.35

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
=> Bump to v3.0.36

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
=> Bump to v3.0.37

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
=> Bump to v3.0.38

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
=> Bump to v3.0.39

src/MobileUI/Controls/CarouselItem.xaml, src/MobileUI/Controls/CarouselItem.xaml.cs, src/MobileUI/Features/Quiz/QuizPage.xaml, src/MobileUI/Features/Redeem/RedeemPage.xaml
Closes #845 
Adds an optional ribbon on the carousel to allow adding an "AI Powered" text on the earn page.
Also cleans up CarouselItem with AutoBindable.
**✅ Figure: Ribbon now shows on Earn page carousel**
No
=> ✨ Mobile | Add AI Powered ribbon on Earn page

src/Common/DTOs/Leaderboard/LeaderboardUserDto.cs, src/MobileUI/Features/Activity/ActivityPageViewModel.cs, src/MobileUI/Features/Leaderboard/LeaderViewModel.cs, src/MobileUI/Features/Profile/ProfileViewModelBase.cs
Closes #1066 
Removes http:// and https:// where a user's company URL is displayed.
No
=> 🐛 Mobile | Remove http/https from user titles

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
=> Bump to v3.0.40

.github/workflows/admin-deploy.yml
App registration secrets are expiring soon.
Changed Azure auth from **secrets** to **federated credentials**
Also defined front door variables to fix errors here:
**https://github.com/SSWConsulting/SSW.Rewards.Mobile/actions/runs/11266852551**
No.
=> Admin | Changing Azure auth to federated credentials

.github/workflows/api-main.yml
CORS error in staging environment API
Changed ADMIN_PORTAL_URL variable for staging deployment from
https://staging.rewards.ssw.com.au
to
https://stsswrewardsadminstaging.z8.web.core.windows.net
No
=> 🛠️Staging Deployment - Fix CORS Issue

src/Application/ActivityFeed/Queries/GetActivitiesQuery.cs, src/Application/Common/Extensions/EfCoreLinqExtensions.cs, src/Application/GlobalUsings.cs, src/Application/Leaderboard/Queries/GetFilteredLeaderboardList/GetFilteredLeaderboardList.cs, src/Application/Leaderboard/Queries/GetFilteredLeaderboardList/GetFilteredLeaderboardListQuery.cs, src/Application/Leaderboard/Queries/GetLeaderboardList/GetLeaderboardListQuery.cs, src/Application/PrizeDraw/Queries/GetEligibleUsers.cs, src/Application/Rewards/Commands/ClaimReward/ClaimRewardCommand.cs, src/Application/Rewards/Commands/ClaimRewardForUser/ClaimRewardForUserCommand.cs, src/Application/Rewards/Commands/CreatePendingRedemption/CreatePendingRedemptionCommand.cs, src/Application/Roles/Queries/GetRoles/GetRolesQuery.cs, src/Application/Services/UserService.cs, src/Application/Staff/Queries/GetStaffList/GetStaffListQuery.cs, src/Application/Staff/Queries/GetStaffMemberProfile/GetStaffMemberProfileQuery.cs
✏️ ApplicationInsights currently does not log SQL queries with the logs and when analyzing SQL queries in SQL Server, it's difficult to determine what part of the code called it. TagWithContext should improve visibility and simplify diagnosing performance issues.
✏️ Adding TagWithContext
✏️ No.
=> ♻️ Adding TagWithContext for better SQL query origin visibility

src/AdminUI/Program.cs, src/ApiClient/ConfigureServices.cs, src/ApiClient/Constants.cs, src/WebAPI/ConfigureServices.cs, src/WebAPI/Telemetry/TelemetryConfig.cs, src/WebAPI/Telemetry/WebApiTelemetryInitializer.cs, src/WebAPI/WebAPI.csproj, src/WebAPI/appsettings.json
✏️ #1119 
When diagnosing endpoints with poor performance, we don't have sufficient telemetry to identify which SQL query is causing issues,
✏️ Added additional telemetry.
✏️ Yes, @vladislav-kir
=> 💡 Added telemetry for SQL dependencies and Client Name

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
Needed to bump the version of the mobile app for the deployment
Bump version to 3.0.41
No
=> Bump Mobile App version to 3.0.41

src/Application/Network/Queries/GetNetworkProfileList/GetNetworkProfileListQuery.cs, src/Common/DTOs/Network/NetworkProfileDto.cs, src/MobileUI/Features/Network/NetworkPageViewModel.cs
https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/1143
1. Changed tab from "Following" to "Scanned"
2. Changed tab from "Followers" to "Scanned me"
3. Changed tab from "To Meet" to "Valuable"
4. Valuable tab - change order to sort by Points value.
No
**Figure: Before - Staff ordered alphabetically**
**Figure: Now - Staff ordered by points value**
=> 💄 Network Page - Change Tab names and order

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
Had to update the version number to deploy to app centre
Updated the version number
No
=> Mobile App - bump the version up

_docs/Instructions-Compile.md
✏️ Going through F5 experience
✏️ Added a step about .NET SDK version
✏️ No
=> ✏️ Add SDK version

_docs/Instructions-Compile.md
✏️ F5 experience
✏️ Added steps if solution fails to load
✏️ No
=> ✏️ Added steps if solution fails to load

infra/modules/webapp.bicep
✏️ #1169
✏️ URL for health check
✏️ @chrisschultzssw
=> 💚 Changing health URL for Web API

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
✏️ New release to appstore
✏️ Updating version to 3.0.43
No
=> Mobile App - Update version to 3.0.43

.github/workflows/admin-build.yml
https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/1145
admin-build:
- remove Build step
- remove --no-build option from Publish step
No
=> 🛠️🔥Admin Portal - fix build action

.github/workflows/admin-deploy.yml, .github/workflows/admin-main.yml
…n dev and staging?)
✏️ #1145 
✏️ We don't use dev for other apps and temporarily we can clear Azure Front Door cache manually.
✏️ Yes, @vladislav-kir
=> 💚 Disabling dev (not used?) and Front Door cache purge

.github/workflows/admin-deploy.yml
…g because of a missing \
✏️ Fixing admin staging deployment
✏️ Verbose output
✏️ No.
=> 💚 See if we can get more info with verbose flag

.github/workflows/admin-deploy.yml
Removed experimental flag "--verbose"
✏️ Fixing Admin build
✏️ Trying to fix Admin build
✏️ No.
=> 💚 Fixing AdminUI staging and production deployment

.github/workflows/admin-deploy.yml, .github/workflows/admin-main.yml
✏️ #1145 
Fix was needed for CDN purge because AdminUI wouldn't update otherwise.
✏️ Updated DevOps work-flow and variables.
✏️ No.
**Figure: Deployment was a success!.**
=> 💚 DevOps | Fixed CDN purge workflow

src/MobileUI/Common/ApplicationExtension.cs, src/MobileUI/Features/App.xaml.cs, src/MobileUI/Features/Login/LoginPageViewModel.cs, src/MobileUI/Platforms/Android/MainActivity.cs, src/MobileUI/Services/AuthenticationService.cs
https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/1008
If redirect to mobile app has "token" query - autologin the user for 1 day.
No
=> ⭐Mobile App - process autologin

src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
=> Bump to v3.0.48

global.json
Failing iOS build in pipeline.
Updates the workload to hopefully fix the build 
No
=> Bump workload version

src/MobileUI/Platforms/iOS/Entitlements.plist
Failing iOS deploy
Sets aps-environment entitlement to production
No
=> Set aps-environment to production

.github/workflows/admin-deploy.yml, .github/workflows/admin-main.yml, .github/workflows/api-az-deploy.yml, .github/workflows/api-main.yml, infra/main.bicep, infra/modules/sql.bicep
closes https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/1127
Changed Infrastructure code:
- Staging Database - use Basic SKU
- Production Database - use S0 SKU
No
=> 🛠️ Infrastructure - Update Production Database tier

.github/workflows/ios-build.yml, src/MobileUI/Platforms/iOS/Entitlements.plist, src/MobileUI/Platforms/iOS/Entitlements.production.plist
Production and development need different configs for the Entitlements.plist file
Updates the iOS build workflow to use a production version of the Entitlements.plist file when in production mode
No
=> Update Entitlements in workflow

src/MobileUI/MobileUI.csproj, src/MobileUI/Platforms/Android/AndroidManifest.xml, src/MobileUI/Platforms/iOS/Info.plist
Bumping to v3.0.49
Theoretically, updating the .csproj like this should update the version from one place rather than having to update both the AndroidManifest.xml and the Info.plist... so trialling this here to see if this works as expected.
=> Bump version to v3.0.49

src/Application/Leaderboard/Queries/GetLeaderboardList/GetLeaderboardListQuery.cs, src/Application/Network/Queries/GetNetworkProfileList/GetNetworkProfileListQuery.cs
A null exception in Staging after the last deployment for https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/1154
Added extra null checks
No
=> Fix Incorrect Profile Pictures - extra null checks

src/MobileUI/Features/AboutSSW/AboutSswPage.xaml.cs, src/MobileUI/MobileUI.csproj
Bump to v3.0.50
Also updates the About screen to show the build number
=> Bump to v3.0.50

src/MobileUI/Features/AppShell.xaml, src/MobileUI/Features/AppShell.xaml.cs, src/MobileUI/Features/Scanner/ScanPage.xaml, src/MobileUI/Features/Scanner/ScanViewModel.cs, src/MobileUI/MobileUI.csproj
Closes #1236 
1. Fixes the phone vibrating when non-SSW QR codes are detected.
2. Fixes an issue when scanning user's QR codes and the user's page isn't navigated to correctly. Also cleans up this page slightly.
3. Bumps the version number.
No
=> 🐛 Mobile | Fix vibration on non-SSW QR codes

src/MobileUI/DependencyInjection.cs, src/MobileUI/Features/App.xaml.cs, src/MobileUI/Features/Login/LoginPage.xaml.cs, src/MobileUI/Features/Login/LoginPageViewModel.cs, src/MobileUI/Features/OnBoarding/OnBoardingPage.xaml, src/MobileUI/Features/OnBoarding/OnBoardingPage.xaml.cs, src/MobileUI/Features/OnBoarding/OnBoardingViewModel.cs, src/MobileUI/Features/Settings/SettingsViewModel.cs, src/MobileUI/Services/AuthenticationService.cs, src/MobileUI/Services/FirstRunService.cs
Closes #1235 
Updates the first-run flow to show the onboarding popup on first launch after either login or registration.
No
=> 🐛 Mobile | Show onboarding after registration

src/MobileUI/Features/AboutSSW/AboutSswPage.xaml.cs, src/MobileUI/Features/Activity/ActivityPageViewModel.cs, src/MobileUI/Features/AppShell.xaml, src/MobileUI/Features/AppShell.xaml.cs, src/MobileUI/Features/Flyout/FlyoutHeaderViewModel.cs, src/MobileUI/Features/Profile/MyProfileViewModel.cs, src/MobileUI/Features/Profile/OthersProfileViewModel.cs, src/MobileUI/Features/Profile/ProfilePicturePage.xaml.cs, src/MobileUI/Features/Profile/ProfileViewModelBase.cs, src/MobileUI/Features/Redeem/RedeemRewardPage.xaml.cs, src/MobileUI/Features/Redeem/RedeemViewModel.cs, src/MobileUI/Features/Scanner/ScanPage.xaml, src/MobileUI/Features/Settings/DeleteProfilePage.xaml, src/MobileUI/Features/Settings/DeleteProfilePage.xaml.cs, src/MobileUI/Features/Settings/SettingsViewModel.cs, src/MobileUI/Features/SocialMedia/AddSocialMediaPage.xaml.cs, src/MobileUI/Features/TopBar/TopBarViewModel.cs, src/MobileUI/MobileUI.csproj, src/MobileUI/Services/AuthenticationService.cs
Closes #1215 
1. Updates profile deletion to use a popup and adds email confirmation to allow deletion.
2. Cleans up some existing popup handling as having to manually adjust status bar colour is no longer needed.
3. Updates the MAUI components to fix an issue with button icons not displaying correctly.
4. Updates back button command to match native back button behaviour.
**Figure: New profile deletion popup**
**Figure: Popup requires the correct email to allow deletion**
No
=> ♻️ Mobile | Add email confirmation to profile deletion + cleanup

src/MobileUI/Common/Api/AuthBrowser.cs, src/MobileUI/Common/Converters/StringToSkLottieImageSourceConverter.cs, src/MobileUI/MobileUI.csproj, src/MobileUI/Platforms/iOS/Program.cs, src/MobileUI/Services/AuthenticationService.cs
Bumps up some old and deprecated packages
=> Update outdated packages

src/MobileUI/DependencyInjection.cs
Last PR was missing a change. 😅 This re-commits the missing change.
=> Commit missing change

src/AdminUI/Components/Dialogs/Rewards/AddRewardDialog.razor, src/AdminUI/Components/Dialogs/Rewards/RewardsEditDialog.razor, src/AdminUI/Components/Dialogs/Skills/AddSkillDialog.razor, src/AdminUI/Helpers/PhotoUploadHelper.cs, src/AdminUI/Pages/Skills.razor
https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/1250
- Rewards & Skill images - increase max size to 10 mb.
- Rewards & Skill images - display errors if upload fails
No
=> 🐛 Admin Portal - fix Rewards Image upload issue

.github/workflows/admin-deploy.yml, .github/workflows/admin-main.yml
Admin Portal build error.
Do not pass databaseSkuName in the admin-deploy
No
=> CI/CD - Admin Portal - Fix deployment

src/MobileUI/Common/Converters/NumberToShorthandConverter.cs, src/MobileUI/Features/Leaderboard/LeaderViewModel.cs, src/MobileUI/Features/Leaderboard/LeaderboardPage.xaml, src/MobileUI/Features/Leaderboard/LeaderboardViewModel.cs, src/MobileUI/Services/LeaderService.cs
Issues with https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/1242
- Changing to using the old API endpoint, since that had better perfomance
- Fixing leaderboard display issues
Passing this to @zacharykeeping
=> Leaderboard - incremental load fixes 

src/MobileUI/Features/Scanner/ScanPage.xaml
Testing
Just a small change to the camera zoom buttons to be better spaced out and work better on smaller devices.
No
=> ♻️ Mobile | Tweak zoom buttons

src/AdminUI/App.razor, src/ApiClient/Constants.cs, src/MobileUI/Platforms/iOS/Entitlements.plist, src/MobileUI/Platforms/iOS/Entitlements.production.plist, src/MobileUI/Platforms/iOS/Info.plist
Testing
Small fix to the admin portal not working, and corrects the App Store link and entitlement in the app.
No
=> 🐛 Admin/Mobile | Fix admin portal and App Store link

src/MobileUI/Features/Leaderboard/LeaderboardViewModel.cs
Test
Small change to use list range handling like ReplaceList() and AddList() rather than clearing and adding tracked items to better optimise how the leaderboard list is handled when switching between tabs. This speeds up tab switching and also makes it appear less janky.
No
=> ♻️ Mobile | Optimise leaderboard list handling

.github/workflows/admin-build.yml, src/MobileUI/MauiProgram.cs
Testing
Fixes a small issue with the iOS app not handling the payloads from URL app links correctly.
Includes hidden files in the admin build pipeline to hopefully resolve an issue with the .well-known folder not being deployed. 
No
=> ♻️ Mobile/DevOps | Fix app link handling

README.md
Updated readme with updated features and roadmap with @adamcogan.
✏️ Chat with Adam
✏️ We updated features and added roadmap.
✏️ Yes.
=> 📝 Updated features and roadmap on Readme.md with Adam

src/Application/Leaderboard/LeaderboardService.cs, src/Application/Leaderboard/Queries/GetMobileLeaderbaoard/GetMobileLeaderbaoard.cs, src/Application/Leaderboard/Queries/GetMobileLeaderbaoard/GetMobileLeaderboard.cs, src/Common/DTOs/Leaderboard/LeaderboardUserDto.cs, src/Common/DTOs/Leaderboard/MobileLeaderboardViewModel.cs, src/Common/DTOs/Pagination/IPaginationResult.cs, src/Common/Utils/RegexHelpers.cs, src/MobileUI/Features/Activity/ActivityPageViewModel.cs, src/MobileUI/Features/Leaderboard/LeaderViewModel.cs, src/MobileUI/Features/Leaderboard/LeaderboardPage.xaml.cs, src/MobileUI/Features/Leaderboard/LeaderboardViewModel.cs, src/MobileUI/Features/Login/LoginPageViewModel.cs, src/MobileUI/Features/Profile/ProfileViewModelBase.cs, src/MobileUI/Features/SocialMedia/AddSocialMediaViewModel.cs, src/MobileUI/MauiProgram.cs, src/MobileUI/Services/FileCacheService.cs, src/MobileUI/Services/FirstRunService.cs, src/MobileUI/Services/LeaderService.cs, src/WebAPI/Controllers/LeaderboardController.cs
✏️ #1268 
✏️ Improved startup logic for auth (in progress) and file caching for leaderboard page.
✏️ No.
=> ✨ Added offline support and leaderboard caching

src/MobileUI/Features/Leaderboard/LeaderboardPage.xaml, src/MobileUI/Features/Leaderboard/LeaderboardPage.xaml.cs, src/MobileUI/MobileUI.csproj
Testing
Closes #1284
Just a couple small tweaks that help improve performance on the leaderboard:
1. As discovered in #1307, having an Image with no set size can result in poor performance as it tries to render the full size. This moves the leaderboard Images to AvatarViews with set sizes for better consistency and performance.
2. Disables animations on ScrollTo so finding yourself doesn't take forever if you're low on the leaderboard.
No
=> ♻️ Mobile | Improve leaderboard performance

.github/workflows/api-build.yml, infra/modules/webapp.bicep
Notifications updates
Updates the pipeline to set the Firebase credentials
✏️
=> ♻️ DevOps | Set Firebase credentials in pipeline

src/MobileUI/Features/Redeem/RedeemPage.xaml, src/MobileUI/Features/Redeem/RedeemViewModel.cs
Closes #1297 
Updates the top bar of the Redeem page to include a simple search to filter the items in the list.
**Figure: The top bar should now be less confusing and features a search bar**
**Figure: Searching filters the items in the list**
No
=> ✨ Mobile | Add search to Redeem page

src/MobileUI/MobileUI.csproj
=> ♻️ Mobile | Bump to version 3.0.58

src/WebAPI/ConfigureServices.cs, src/WebAPI/Filters/UrlBlockList.cs, src/WebAPI/Telemetry/WebApiTelemetryInitializer.cs, src/WebAPI/appsettings.json
✏️ A few 499 errors in AppInisghts.
✏️ Added additional filtering down and some .NET 9 performance improvements.
✏️ No.
=> 💚 Reduce 404 and 499 noise in AppInsight part 1.2

src/Application/Notifications/Commands/SendAdminNotificationCommand.cs
… seemed to happen.
✏️ #1350 
✏️ Fixed an issue where if there are 0 people to send, there is no record of the notifications.
✏️ No.
This pull request refactors the logic for querying target user IDs in the `SendAdminNotificationCommand` handler to improve code readability and maintainability. The main change involves extracting the query logic into a new helper method, `GetTargetUserIdsQuery`, and using it throughout the handler.
* **Introduced `GetTargetUserIdsQuery` method**: Extracted the logic for building the query to retrieve target user IDs based on activation status, achievements, roles, and specific user IDs into a separate …
=> 🐛 Fixed a bug when sending notification to 0 users

src/MobileUI/Controls/ProfileStats.xaml, src/MobileUI/Features/Profile/ProfileViewModelBase.cs
Testing
I noticed warnings from the profile page due to an incorrect DataType. I fixed this, and also tweaked the page to fix up inconsistent spacing (such as large gaps if nobody has social media set) and some other general code cleanup.
No
=> ♻️ Mobile | Clean up profile page

src/Application/Achievements/Command/ClaimAchievementForUser/ClaimAchievementForUserCommand.cs, src/Application/Achievements/Command/PostAchievement/PostAchievementCommand.cs, src/Application/Achievements/Notifications/UserMilestoneAchievementCheckRequested.cs, src/Application/Common/Constants/CacheKeys.cs, src/Application/Leaderboard/LeaderboardService.cs, src/Application/System/Commands/Common/MilestoneAchievements.cs, src/Application/System/Commands/Common/SampleDataSeeder.cs
✏️ #536 
✏️ Added code to get Top 100 leaderboard achievement. Also, refactored old code that contained performance issues and subtle bugs (like granting "Scanned person" achievement even if no person was found.
**Figure: Unlocking the achievement as soon as I scan something and I'm in top 100 all time.**
✏️ No.
=> 🐛 Fixed bug where top 100 achievement doesn't happen

src/MobileUI/Features/Redeem/RedeemRewardPage.xaml, src/MobileUI/Features/Redeem/RedeemRewardViewModel.cs, src/MobileUI/Models/Reward.cs, src/MobileUI/Services/RewardService.cs
Closes #1157 
Updates the redeem page to allow redeeming digital items without needing to input an address. Also cleans up the code a bit and adds some confirmation.
No
=> ♻️ Mobile | Redeem digital rewards

src/MobileUI/Models/AuthErrorType.cs, src/MobileUI/Services/Authentication/AuthStorageService.cs, src/MobileUI/Services/Authentication/OidcAuthenticationProvider.cs, src/MobileUI/Services/Authentication/TokenManager.cs, src/MobileUI/Services/AuthenticationService.cs
Testing
Fixes up some issues in regards to the refresh login flow where it might not handle the server response correctly, and also improves this flow in offline mode.
No
=> 🐛 Mobile | Fix refresh flow issues

src/Infrastructure/Persistence/Migrations/20250704035942_AddAchievementAndStaffMemberSoftDelete.cs
✏️  #1381 
✏️ Order of changes wasn't quite correct and migration failed. Due no integration tests, it was difficult to retest EF Core migrations.
✏️ No.
=> 🐛 Fixing migration steps

src/MobileUI/Features/Profile/MyProfileViewModel.cs, src/MobileUI/Features/Profile/OthersProfileViewModel.cs, src/MobileUI/Features/Profile/ProfileViewModelBase.cs, src/MobileUI/Services/UserService.cs
Closes #1311 
Adds offline support to all profile pages, which works by first trying to load from cache if available then attempts to load fresh data in the background (which then updates the cache).
No
=> ✨ Mobile | Add offline support to profile pages

src/AdminUI/Pages/Notifications.razor, src/AdminUI/Pages/Notifications.razor.cs, src/AdminUI/Pages/SendNotification.razor, src/AdminUI/Pages/SendNotification.razor.cs, src/ApiClient/Services/INotificationsService.cs
✏️  #1392
✏️ Changed Archived to Deleted and UI label changes before bigger changes are made as part of #1392.
✏️ No.
**Figure: Updated labels**
=> ✨ Update notification management: rename archive to delete

.github/workflows/admin-deploy.yml, .github/workflows/android-build.yml, .github/workflows/api-az-deploy.yml
#1395
Replaces backslashes in paths with forward slashes in our GitHub workflows.
No
=> 🐛 CI/CD | Replace backslashes with forward slashes in workflows

src/Application/Achievements/Command/PostAchievement/PostAchievementCommand.cs, src/Application/Staff/Commands/UpsertStaffMemberProfile/UpsertStaffMemberProfileCommand.cs, src/MobileUI/Features/Scanner/ScanViewModel.cs, src/WebAPI/Controllers/StaffController.cs
Closes #1399
Fixes a few issues discovered after trying to set up a new profile:
1. Updates the scanning logic in the app to use a semaphore to prevent scan results being triggered multiple times.
2. Fixes up some logic to prevent achievements being recorded multiple times when they shouldn't be allowed, and prevent creating new profiles if that user's email already exists in the system.
No
=> 🐛 Mobile/API | Duplicate scan and profile fix

src/MobileUI/Controls/ProfileActivity.xaml, src/MobileUI/Features/Profile/MyProfileViewModel.cs, src/MobileUI/Features/Profile/OthersProfileViewModel.cs, src/MobileUI/Features/Profile/ProfileViewModelBase.cs, src/MobileUI/Features/Scanner/ScanPage.xaml
Closes #1107 
Updates profile pages to show all activity in one list. If a user is on their own page and there's no activity there will be a button that can take them to the scan page. Also cleans up these files a bit.
No
=> ♻️ Mobile | Consolidate profile list activity

src/WebAPI/WebAPI.csproj
=> Bump Azure.Identity
