DevOps/infrastructure.json

added in all the object id's for the team into KeyVault so that I don't have to manually add people back in after a deployment.
Whenever keyvault is "updated" from a deployment it resets all the access policies. This should fix that pain.

add keyvault access policies for the team

---

Xamarin/SSW.Consulting/SSW.Consulting/Services/UserService.cs

changed await Task.Run(Auth.SignOut) to Auth.SignOut()

Fix await build error on ios and android

---

Xamarin/SSW.Consulting/SSW.Consulting/Constants.cs
Xamarin/SSW.Consulting/SSW.Consulting/ViewModels/ProfileViewModel.cs
Xamarin/SSW.Consulting/SSW.Consulting/Views/Profile.xaml

In PR#72 we changed the profile from using ListView to a custom control called RepeaterView. This removed a bunch of hacky code - using rows as headers and magic string property values to denote to the UI that certain rows were header rows - but doesn't have the nice waterfall list loading effect.
This is an interim improvement and adds an activity indicator while the RepeaterView is loading data. Longer term a nicer loading effect (possibly a skeleton screen with a shimmer effect) can be used.

Added loading indicator to profile page

---

API/SSW.Rewards/Services/CurrentUserService.cs

fix profile pic url - empty string creates invalid Uri in Leaderboard AutoMapper

fix profile pic url - empty string creates invalid Uri in Leaderboard

---

azure-pipelines.yml

This change will allow this pipeline to run on the on-premises agent pool, which does not have any Linux servers

updated agent pool in pipeline from ubuntu to windows

---

Xamarin/SSW.Rewards/SSW.Rewards.Android/MainActivity.cs
Xamarin/SSW.Rewards/SSW.Rewards.Android/SSW.Rewards.Android.csproj
Xamarin/SSW.Rewards/SSW.Rewards.iOS/SSW.Rewards.iOS.csproj
Xamarin/SSW.Rewards/SSW.Rewards/Constants.cs
Xamarin/SSW.Rewards/SSW.Rewards/SSW.Rewards.csproj

- Updated some packages, note `Microsoft.Identity.Client`
- Upgraded `Xamarin.Forms` from 4.8 to 5 for MSAL packages to work correctly.
- Upgraded `Rg.Plugins.Popup` from 2.0 to 2.1 for popups to work correctly in iOS. 
- Revert ApiBaseUrl from local ngrok to https://sswconsulting-dev.azurewebsites.net

Update MSAL packages and revert ApiBaseUrl

---

Xamarin/SSW.Rewards/SSW.Rewards.Android/Properties/AndroidManifest.xml
Xamarin/SSW.Rewards/SSW.Rewards.Android/SSW.Rewards.Android.csproj

- Updates the Android TargetFrameworkVersion from v10 to v12 (Leaving the minimum at v7)
- Adds the `x86_64` architecture to the Android builds
`SingleOrDefaultAsync` - Throws an "Enumerator failed to MoveNextAsync" when there is more than 1 record?
`_context.Users` currently brings back a duplicate of the current user (Tested locally). 
https://github.com/SSWConsulting/SSW.Rewards/blob/3c0cea3291a728bdb50d2f9d7b2f602326dc1be5/API/SSW.Rewards.Application/User/Queries/GetCurrentUser/GetCurrentUserQuery.cs#L49

⚠️Android - Upgrade TargetFrameworkVersion to v12 & Add supported windows architecture

---

Xamarin/SSW.Rewards/SSW.Rewards/ViewModels/LoginPageViewModel.cs

Comment out `Crashes.TrackError()` in LoginPageVM - test to see if the auth bug has anything to do with AppCenter.

Comment out `Crashes.TrackError()` in LoginPageVM

---

.github/workflows/xamarin.yml
Xamarin/SSW.Rewards/SSW.Rewards.Android/Properties/AndroidManifest.xml
Xamarin/SSW.Rewards/SSW.Rewards.iOS/Info.plist

Bumping app versions for both Android and iOS as releases won't build for duplicated version number.
Add iOS release notes to fix build error in:
https://github.com/SSWConsulting/SSW.Rewards/runs/5981256844?check_suite_focus=true
_*apparently the log can't be found now, but it did indicate missing iOS release notes._

Bump app version and add release notes for iOS

---

Xamarin/SSW.Rewards/SSW.Rewards/ViewModels/LoginPageViewModel.cs

- Sets isRunning to false, allowing the sign in button to be clickable again

🐛Auth bug 

---

.github/workflows/xamarin.yml

This PR handles auto incrementation of app build versions for both iOS and Android.
Build version name will be based on `release tag` on branch. Build version number will be based on `count of commits` under the release tag.
Action `damienaicheh/extract-version-from-tag-action@v1.0.0` accepts only tags in the format of `x.x.x` or `vx.x.x` and currently spits out string in the format of `x.x` to be assigned to iOS and Android version names, just to be consistent with the previous build version name formatting.
Release tag `1.78.0` and has `2 commits` associated with the tag upon merge into staging.
__iOS__
Bundle versions string(short) = 1.78
Bundle version = 1.2 (1.x)
__Android__
Version name = 1.78
Version number = 2

Auto increment app build versions for both iOS and Android

---

API/SSW.Rewards.Application/Notifications/Commands/DeleteInstallation/DeleteInstallationCommand.cs
API/SSW.Rewards.Application/Notifications/Commands/RequestNotification/RequestNotificationCommand.cs
API/SSW.Rewards/Controllers/NotificationsController.cs
API/SSW.Rewards/nswag/SSW-Rewards-client.ts
API/SSW.Rewards/wwwroot/api/specification.json
Xamarin/SSW.Rewards/SSW.Rewards/Helpers/ApiClient.g.cs

Need this PR to be merged so that auth is temporarily gone for only Push Notifications endpoints, allowing me to test to see app is working with Push Notifications in the dev environment.
Things I have done specifically in this PR are:
- Commented out the db stuff inside `RequestNotificationCommand` as currently missing Notification table
- Fixed error 500 upon calling `/api/Notifications/DeleteInstallation/{installationId}` API endpoint
- Added [AllowAnonymous] to `NotificationsController` to bypass auth for test.

Fix DeleteInstallation endpoint and temp auth workaround for testing Push Notifications in Dev 

---

API/SSW.Rewards/SSW.Rewards.WebAPI.csproj

Reverts SSWConsulting/SSW.Rewards#220
Suggested version is incompatible. This will be resolved when we upgrade the API to .NET 6.

Revert "Bump Microsoft.AspNetCore.Authentication.JwtBearer from 3.0.0 to 3.1.18 in /API/SSW.Rewards"

---

Xamarin/SSW.Rewards/SSW.Rewards/App.xaml
Xamarin/SSW.Rewards/SSW.Rewards/AppShell.xaml
Xamarin/SSW.Rewards/SSW.Rewards/AppShell.xaml.cs
Xamarin/SSW.Rewards/SSW.Rewards/Controls/FlyoutHeader.xaml
Xamarin/SSW.Rewards/SSW.Rewards/Pages/ProfilePage.xaml
Xamarin/SSW.Rewards/SSW.Rewards/ViewModels/FlyoutHeaderViewModel.cs

This PR updates the menu to the V2 design
**Figure: Non-staff user sees the Join SSW menu item**
**Figure: Staff user sees the QR code menu item instead of Join, and sees the four squares next to their name in the header**

💄 Update menu to v2 design

---

API/SSW.Rewards/wwwroot/api/specification.json
Xamarin/SSW.Rewards/SSW.Rewards/PopupPages/CameraPage.xaml
Xamarin/SSW.Rewards/SSW.Rewards/ViewModels/CameraPageViewModel.cs

cc: @leehawkinsssw 
- Updates to the new UI
- Fixes camera button being enabled before a picture has been selected (https://github.com/SSWConsulting/SSW.Rewards/issues/298)
**Figure: With no photo selected, the "Use this picture" button is disabled**
**Figure: With a picture selected, the button is enabled**

♻️ Camera Page Updates

---

src/SSW.Rewards/Pages/ProfilePage.xaml

Refactored the component which displays profile info.
Now all elements use the center of the circle as a reference point. Previously those labels and images were placed from top to bottom.
Fixes issue #407

🐛UI | Stars and Points on welcome page are not fully visible

---

src/SSW.Rewards/Platforms/iOS/Info.plist
src/SSW.Rewards/SSW.Rewards.Mobile.csproj
src/SSW.Rewards/SSW.Rewards.sln

Two major issues identified with the last version sent to TestFlight:
* Incorrect icon scaling
* App crashes at startup

Bumped iOS version, fixed icon scaling

---

src/SSW.Rewards/Pages/ProfilePage.xaml

In testing the most recent build, two issues were identified on iOS only. The tab bar hides the `IndicatorView` and the last row of achievements.
The issue occurs due to a bug in .NET MAUI (see: https://github.com/dotnet/maui/issues/17817); this provides a workaround.
Fixes #453 
Fixes #454

Fix ios tabbar overlay

---

src/SSW.Rewards/Pages/PeoplePage.xaml
src/SSW.Rewards/Platforms/iOS/Info.plist

Prior to adding the search bar, all rows on the People page were proportional. Since adding the search bar, which is fixed height, the proportional rows will adjust according to each other but also the fixed height row.
This allows the bio row to grow and shrink depending on the size of its content (in this case dictated by the length of the bio).
Making this row also fixed height resolves the issue.
Fixes #458

Made bio in People profiles fixed height

---

src/SSW.Rewards/Pages/ProfilePages/MyProfilePage.xaml.cs
src/SSW.Rewards/Pages/ProfilePages/OthersProfilePage.xaml.cs
src/SSW.Rewards/Platforms/iOS/Info.plist
src/SSW.Rewards/ViewModels/ProfileViewModels/ProfileViewModelBase.cs

Minor bug in latest version - in the profile ViewModels, Ondisappearing deregisters WeakReferenceMessenger recipients. This means that after you navigate away from your own profile, you can't tap achievements anymore.
Kept this but moved the registration from ctor to OnAppearing.

Fix unregister notifications

---

_docs/Instructions-Compile.md
src/SSW.Rewards/SSW.Rewards.Mobile.csproj

Cc: @Anton-Polkanov @zacharykeeping 
Updates `Instructions-Compile.md`
The current F5 Experience hasn't been updated since we made the switch over to MAUI.
I think that it could be worth directing people to run this quick setup for MAUI on .NET 8 from M$. Most of the hard setup is for the API repo. But I could be missing a step here.
https://learn.microsoft.com/en-us/dotnet/maui/get-started/first-app?view=net-maui-8.0&tabs=vsmac&pivots=devices-android

update f5 experience

---

src/MobileUI/Services/IAuthenticationService.cs
src/MobileUI/ViewModels/LoginPageViewModel.cs

#544
1. Fixes a bug where alerts for log in issues are never displayed on iOS as they occur during the closing animation for the Safari web view and both never display the alert and never resolve the await call. This just adds a delay for iOS but there's probably a better solution here that I'm unaware of.
2. Fixes an issue where a user can be caught in a perpetual log in loop where either the log in spinner continues indefinitely or hitting the log in button results in the web view window opening then immediately closing and never allowing the user to attempt logging in again. This change just clears credentials upon an error then prompts for login on next execution.
> 3. Did you …

🐛 Mobile - Log in auth fixes

---

infra/modules/sql.bicep

✏️ Fixes #585 
✏️ The SQL server administrators were moved out of direct assignment within the SQL Server resource in the bicep template, and added as their own resource with the SQL server set as the parent.
✏️ N/A

Move SQL administrators to separate resource

---

src/MobileUI/Pages/LeaderboardPage.xaml
src/MobileUI/Pages/LeaderboardPage.xaml.cs
src/MobileUI/ViewModels/LeaderBoardViewModel.cs

✏️ Updates the Leaderboard page to the layout defined in #558 
✏️ 
* Header section removed
* Search removed
* Scroll buttons removed
* Row definitions updated
* Unused code removed
✏️ N/A

V2 layout and cleaned up unused code

---

src/Application/Common/Interfaces/IQuizGPTService.cs
src/Application/Quizzes/Commands/BeginQuiz/BeginQuizCommand.cs
src/Application/Quizzes/Commands/SubmitAnswerCommand/QuizGPTRequestDto.cs
src/Application/Quizzes/Commands/SubmitAnswerCommand/QuizGPTResponseDto.cs
src/Application/Quizzes/Commands/SubmitAnswerCommand/SubmitAnswerCommand.cs
src/Application/Quizzes/Commands/SubmitAnswerCommand/SubmitAnswerCommandValidator.cs
src/Application/Quizzes/Queries/CheckQuizCompletion/CheckQuizCompletionQuery.cs
src/Application/Quizzes/Queries/GetQuizListForUser/GetQuizListForUser.cs
src/Application/Quizzes/Queries/GetQuizQuestionsBySubmissionId/GetQuizQuestionsBySubmissionIdQuery.cs
src/Application/Quizzes/Queries/GetQuizResults/GetQuizResultsQuery.cs
src/Common/DTOs/Quizzes/BeginQuizDto.cs
src/Common/DTOs/Quizzes/QuestionResultDto.cs
src/Common/DTOs/Quizzes/QuizQuestionDto.cs
src/Common/DTOs/Quizzes/QuizResultDto.cs
src/Common/DTOs/Quizzes/SubmitQuizAnswerDto.cs
src/Common/DTOs/Quizzes/SubmittedAnswerDto.cs
src/Domain/Entities/CompletedQuiz.cs
src/Domain/Entities/QuizQuestion.cs
src/Domain/Entities/SubmittedQuizAnswer.cs
src/Infrastructure/ConfigureServices.cs
src/Infrastructure/Options/GPTServiceOptions.cs
src/Infrastructure/Persistence/Configurations/QuizConfiguration.cs
src/Infrastructure/Persistence/Migrations/20240122031047_AddGPTQuizFields.Designer.cs
src/Infrastructure/Persistence/Migrations/20240122031047_AddGPTQuizFields.cs
src/Infrastructure/Services/QuizGPTService.cs
src/WebAPI/Controllers/QuizzesController.cs
src/WebAPI/appsettings.json

This is part 1 of the back-end work. Next step is to make the `SubmitAnswer` endpoint non-blocking, but that can be done as a separate PR.
**WARNING: New `GPTServiceOptions` in `appSettings.json` is a local URL until we have the SSW Azure OpenAI service spun up.**
Adding GPT quiz API endpoints
* Added new endpoints to QuizzesController, along with corresponding commands/queries.
* Schema changes to include new GPT-returned fields
Sorta kinda.

Lc quizgpt backend

---

_docs/Instructions-Compile.md
docker-compose.yml
up.ps1

✏️ Branch protection rules were inadvertently overwritten when we added `settings.yml` to the repo. Accidental pushes to main have then occurred; this PR reverts them.
✏️ Revert to the last merged commit prior to accidental pushes to main
✏️ I worked with @lukecookssw and @tkapa

Revert accidental pushes to main

---

src/Infrastructure/Services/QuizGPTService.cs

Spotted missing field population.
`CreatedUtc` is now being set on creating a new Submitted Answer.
✏️

Added missing field to db create

---

_docs/Instructions-Compile.md
src/MobileUI/Pages/ScanPage.xaml.cs
src/MobileUI/ViewModels/ScanResultViewModel.cs

✏️ Users reported a bug that the scanner is not working in some cases. Happens on both Android and iOS
✏️  1. Updated README
2. Every time the popup opens - we disable the scanner; when it closes - we enable it again. I changed the order of operations - we need to close the ScanResult popup first and only after that enable scanning, because double taps and long taps lead to `PopAllAsync` closing current and the next appearing popup. Hence, the scanner is not enabled again.
✏️  No

🐛 Mobile | Fix scanner bug

---

src/MobileUI/Controls/PointsButton.xaml
src/MobileUI/Controls/PointsButton.xaml.cs
src/MobileUI/Pages/EarnDetailsPage.xaml
src/MobileUI/Pages/EarnPage.xaml
src/MobileUI/Pages/EarnPage.xaml.cs
src/MobileUI/ViewModels/EarnViewModel.cs

Related to #559
Adds tweaks and missing features to the Earn page that didn't quite make it to PR #606
1. Adds auto scrolling to the carousel
2. Adds a disabled visual state to the GO buttons for when a quiz is already passed
3. Changes Editor to Entry for answer input to fix issues with text disappearing under the keyboard and misaligned placeholder text, and allows for more intuitive entry with use of the Return key.
4. Tweaks margins and other design elements like carousel indicators to better align with the V3 mockups.
5. Adds animation to Earn page load
**Figure: Tweaked design to better match mockups**
**Figure: Improved input handling and display**
> 3. Did you do pair or …

♻️ Mobile - V3 Earn page improvements

---

src/MobileUI/Controls/Snackbar.xaml
src/MobileUI/Controls/Snackbar.xaml.cs

align icon vertically on Android
✏️ Task 1 on #609
✏️ Use `await CloseAsync` instead of `Close`
✏️ Align achievement icon in the snackbar vertically
✏️ No

🐛 Mobile | Stabilisation before release | Fix snackbar

---

src/MobileUI/Pages/LeaderboardPage.xaml
src/MobileUI/ViewModels/LeaderBoardViewModel.cs

✏️ #609 
✏️ Set properties to `null`, so that `PropertyChanged` event is triggered
✏️ No

🐛 Mobile | Stabilisation before release | Fix Leaderboard not updating

---

src/Application/Quizzes/Commands/SubmitAnswerCommand/QuizGPTRequestDto.cs
src/Application/Quizzes/Commands/SubmitAnswerCommand/QuizGPTResponseDto.cs
src/Application/Quizzes/Commands/SubmitAnswerCommand/SubmitAnswerCommand.cs

GPT gets confused with difficult questions. We now supply it a `BenchmarkAnswer` (which is the text of the correct `QuizAnswer` entity for the given question).
Additional field - `BenchmarkAnswer` is being supplied to QuizGPT.
No

added benchmark answer to QuizGPT integration

---

src/MobileUI/Services/UserService.cs

Part of #621
Always sets preferences from user data even if the new data doesn't exist so that old preferences aren't used. In this instance, a non-SSW account logging in after an SSW account meant the QR code was loading from the previous account's preferences as the new account didn't have data to overwrite it.
No

🐛 Mobile - Fix QR code showing for non-SSW accounts

---

src/MobileUI/Pages/EarnDetailsPage.xaml.cs
src/MobileUI/ViewModels/EarnDetailsViewModel.cs

Closes #629
Fixes previous quiz thumbnail displaying briefly when switching to another quiz.
No.

🐛 Mobile - Fix wrong quiz logo showing briefly

---

src/MobileUI/ViewModels/EarnDetailsViewModel.cs

Just a small issue I noticed when testing where a user could submit an answer multiple times which results in an error popup. Part of #621
This is a small tweak to prevent a user from submitting an answer twice and also where the final answer could be submitted twice when retrying the final quiz completion check.
No

🐛 Mobile - Prevent double submission for quiz answers

---

src/MobileUI/PopupPages/LinkSocial.xaml

Closes #627
These popups weren't working due to an issue with Frame in .NET MAUI on Android (which is effectively deprecated). Moving to Border fixes this.
No

🐛 Mobile - Fix achievement popups appearing blank on Android

---

src/ApiClient/Services/IPrizeDrawService.cs
src/WebAPI/Controllers/LeaderboardController.cs

✏️  Found an issue with Admin portal while browsing
✏️ Fixes the `IPrizeDrawService` endpoint to use `GET` and be consistent with the `GetEligibleUsers`
✏️ No

Fix prize draw

---

src/MobileUI/Pages/EarnPage.xaml.cs

Part of #621
Fixes an issue where changing pages after loading the Earn page can result in the autoscroll of the carousel acting sporadically.
No

🐛 Mobile - Fix Earn carousel when switching pages

---

src/MobileUI/ViewModels/LoginPageViewModel.cs

Part of #621
We previously added a workaround on iOS which adds a Task.Delay() before displaying an alert after an exception in the login flow as it could result in the alert never displaying and execution never continuing. This should have been added to the refresh flow but was missing, so this adds it there. This may resolve issues with the login being stuck on a spinner on iOS.
No

🐛 Mobile | Fix alert potentially not displaying in refresh flow on iOS

---

src/MobileUI/Pages/EarnPage.xaml

Email from @adamcogan 
Completed quizzes now have greyed out text and a new tick in the quiz list to better stand out.
**Figure: Updated look for completed quizzes**
No

♻️ Mobile | Dim text and add tick on completed quizzes

---

src/MobileUI/Controls/ProfileActivityItem.xaml
src/MobileUI/Controls/ProfileStats.xaml
src/MobileUI/Pages/ProfilePages/OthersProfilePage.xaml

Mainly triggered by Adam's screenshots from his emails, where his phone is set to a larger system text size and is causing many layouts to break. 
**Figure: Layout issues with increased system text size**
Part of V3 profile changes #613 
Improves handling of varying text sizes on the profile page to improve accessibility.
**Figure: Me page with max system text size**
**Figure: Other profile page with max system text size**
No

♻️ Mobile | Improve V3 profile text size handling

---

src/MobileUI/Controls/ProfileStats.xaml
src/MobileUI/Services/DevService.cs

I noticed an issue with the new Skill Set section on the V3 profile page where large amounts of text on skill names could mess up the layout.
Related to #613
This allows the skill names to break to new lines to prevent the layout being messed up, and adjusts all skill heights accordingly.
Also includes a fix where it could crash if it can't find a profile.
**Figure: Skill text now wraps to new lines if necessary**
No

🐛 Mobile | Fix for profile skill text overflow

---

src/AdminUI/Program.cs
src/AdminUI/RolesClaimsPrincipalFactory.cs

✏️ Found a bug on Admin deployment.
SSW.Identity returns Roles in the Token as a string array, which the Blazor `AuthorizeView` doesn't like. 
I found this issue that has a solution https://github.com/dotnet/aspnetcore/issues/21836
✏️ Added middleware to the Oidc flow to Remove the Role claims from the user's identity, and re-add them as individual role claims.
✏️ No

🐛 Admin | Fix Authorize View Issue with Array Role Claim

---

src/MobileUI/MauiProgram.cs
src/MobileUI/MobileUI.csproj
src/MobileUI/Pages/EarnDetailsPage.xaml
src/MobileUI/Pages/EarnDetailsPage.xaml.cs
src/MobileUI/Pages/PeoplePage.xaml
src/MobileUI/Platforms/Android/Resources/values/colors.xml
src/MobileUI/ViewModels/EarnDetailsViewModel.cs

✏️ The input box for quizzes was single line. Fixes the "OS keyboard and editor (enable multiline)" task on #615 
✏️ 
The input box is now multiline
The input box is transparent, hence the page feels lighter
Removed underline from the input box on Android
The cursor color is Red
The keyboard hides when the user clicks outside of it on the PeoplePage
Upgraded MAUI to the latest version
Replaced `ICommand` with `RelayCommand`
**Figure 1:** This is how the multiline input box looks like now.
**Figure 2:** The multiline input box scales up and down when user adds or deletes text.
**Figure 3:** The keyboard has a Done button at the right top corner of the iOS keyboard.
> 3. Did you do …

✨ Mobile | Fix the answer field for quizzes

---

src/Application/Staff/Queries/GetStaffList/Mapping.cs
src/Common/DTOs/Staff/StaffSkillDto.cs
src/MobileUI/Controls/ProfileStats.xaml

Part of #613 
Hooks up skill thumbnails to the profile page, with a fallback icon if it does not exist.
**Figure: Skill thumbnails now show if they exist**
No

✨ Mobile | Show thumbnails on skills on profile page

---

src/MobileUI/Controls/FlyoutHeader.xaml

✏️ Incorrect UI
✏️ Hide a label and divider when `IsStaff` is `false`
✏️ No
**Figure:** ❌ Before - "Scan me" and divider are not relevant for the user
**Figure:** ✅ Before - "Scan me" and divider are hidden

✨ Mobile | Hide Label and Divider for non-SSW users

---

src/MobileUI/Platforms/Android/AndroidManifest.xml
src/MobileUI/Platforms/iOS/Info.plist
src/MobileUI/Services/IAuthenticationService.cs

✏️  Email from @adamcogan subject **URGENT 🔥 rewards auth bug - can’t get in** + Teams message from @joshbermanssw
✏️ In the method that uses the refresh token to get a new access token, if it fails, we try to get OIDC Client to perform a silent front channel login. This is causing errors, so we've removed it and revert to an interactive login instead.
✏️  Issue discussed with @tkapa and @Anton-Polkanov

Remove silent front channel authentication attempt on failed token refresh

---

src/MobileUI/MauiProgram.cs
src/MobileUI/Services/IPermissionsService.cs
src/MobileUI/Services/PermissionsService.cs
src/MobileUI/ViewModels/CameraPageViewModel.cs
src/MobileUI/ViewModels/ProfileViewModels/MyProfileViewModel.cs
src/MobileUI/ViewModels/ProfileViewModels/OthersProfileViewModel.cs
src/MobileUI/ViewModels/ProfileViewModels/ProfileViewModelBase.cs
src/MobileUI/ViewModels/TopBarViewModel.cs

✏️ App crash on iOS. #777 
✏️ Added `PermissionsService` which handles permission requests slightly differently for Android and iOS:
- Android will display the request again and again until it's accepted by the user.
- iOS won't display the request once it's rejected, so the user has to give permissions via Settings.
https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/11dcad80-d3e5-45d5-826b-4fffcc1ead0e
https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/44ddc04e-1dd0-4651-be23-6f4e585ad35c
✏️ No

🐛 Mobile | Handle decline of camera permission

---

src/Infrastructure/Persistence/Interceptors/AuditableEntitySaveChangesInterceptor.cs

✏️ #749 - CreatedUTC not captured for new users
✏️ Added `BaseEntity` to the interceptor. This a workaround - the `User` entity needs to be properly refactored to inherit `BaseAuditableEntity`. And we need to carefully consider the use case for both base enities.
**Figure A new user account has this field populated correctly**
✏️ No

Adds base entity to the interceptor

---

src/MobileUI/Services/IAuthenticationService.cs

✏️ #731 
✏️ 
- If token refresh has failed for some reason and user successfully signed in using their credentials, we need to close the login page and redirect them on the tabbed page
- After logout we need to preserve the `FirstRun` flag to avoid showing the Onboarding page multiple times
✏️ No

🐛Mobile | Handle successful signIn after unsuccessful token refresh

---

src/Infrastructure/Services/RewardSender.cs

✏️ Redeem emails are going to the Rewards team
✏️ Emails now going to marketing
✏️ No

Send redeem emails to marketing

---

src/MobileUI/Controls/CarouselItem.xaml
src/MobileUI/Controls/CarouselItem.xaml.cs
src/MobileUI/Pages/RedeemPage.xaml

#792 
Hooks up the correct button command to carousel items on the redeem page, and sets it to handle the disabled state correctly.
No

🐛 Mobile | Hook up button command to redeem page carousel item

---

src/MobileUI/MobileUI.csproj
src/MobileUI/Services/PermissionsService.cs

✏️ #777 
✏️ Enabled Mono interpreter for System.Collections.Immutable on iOS in Release mode. For details, see the link to an issue in the MAUI Community Toolkit repo on #777.
✏️ No

🐛 Mobile | Enable Mono interpreter for single library on iOS in Release mode

---

src/MobileUI/Controls/Snackbar.xaml
src/MobileUI/Controls/Snackbar.xaml.cs
src/MobileUI/Pages/EarnPage.xaml
src/MobileUI/ViewModels/EarnDetailsViewModel.cs
src/MobileUI/ViewModels/EarnViewModel.cs

Closes #793
1. Fixes text overlaying the points icon in the snackbar
2. Fixes points showing as 0 in the snackbar 
3. Only shows the snackbar after the loading screen has closed
4. Fix passed status not showing when completing a quiz by allowing data to refresh on appearing
**❌ Figure: Previous snackbar with layout issues and loading screen still present**
**✅ Figure: Improved snackbar**
No

🐛 Mobile | Quiz flow fixes

---

src/MobileUI/Pages/LeaderboardPage.xaml
src/MobileUI/ViewModels/LeaderBoardViewModel.cs

Closes #778 
Updates the pull-to-refresh functionality on the leaderboard page to not pull down the whole page but only the content below the filter. Also fixes an issue where the leaderboard can be loaded multiple times on initial load, which can mess up the animations.
No

🐛 Mobile | Set leaderboard pull-to-refresh below filter

---

src/AdminUI/AdminUI.csproj
src/AdminUI/Components/Dialogs/Users/DeleteUserDialog.razor
src/AdminUI/Pages/ProfileDeletions.razor
src/AdminUI/Shared/NavMenu.razor
src/ApiClient/Services/IUserAdminService.cs
src/Application/Common/Interfaces/IApplicationDbContext.cs
src/Application/Common/Interfaces/IEmailService.cs
src/Application/Users/Commands/AdminDeleteProfile/AdminDeleteProfileCommand.cs
src/Application/Users/Commands/AdminDeleteProfile/AdminDeleteProfileCommandValidator.cs
src/Application/Users/Commands/Common/DeleteProfileEmail.cs
src/Application/Users/Commands/DeleteMyProfile/DeleteMyProfileCommand.cs
src/Application/Users/Queries/AdminGetProfileDeletionRequests/AdminGetProfileDeletionRequestsQuery.cs
src/Application/Users/Queries/AdminGetProfileDeletionRequests/Mapping.cs
src/Common/DTOs/Users/AdminDeleteProfileDto.cs
src/Common/DTOs/Users/ProfileDeletionRequestDto.cs
src/Domain/Entities/OpenProfileDeletionRequest.cs
src/Domain/Entities/User.cs
src/Infrastructure/Persistence/ApplicationDbContext.cs
src/Infrastructure/Persistence/Migrations/20240327052800_AddProfileDeletionRequests.Designer.cs
src/Infrastructure/Persistence/Migrations/20240327052800_AddProfileDeletionRequests.cs
src/Infrastructure/Services/EmailService.cs
src/WebAPI/Controllers/UserController.cs
tests/Application.UnitTests/Common/Mappings/MappingTests.cs

✏️ We need to provide users with a way to request their profile is deleted to comply with App Store requirements and privacy legislation. Currently, this is done manually in the database.
✏️ UI and logic added to manage deletion requests via the admin portal
✏️ NA

Delete user profiles

---

src/MobileUI/Services/IUserService.cs
src/MobileUI/Services/UserService.cs
src/MobileUI/ViewModels/FlyoutHeaderViewModel.cs
src/MobileUI/ViewModels/LeaderBoardViewModel.cs
src/MobileUI/ViewModels/ProfileViewModels/MyProfileViewModel.cs

✏️ Closes #817 
✏️ Made `Rank` reactive with the source of truth in `userService`
✏️ No
https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/ce04cb80-e172-4304-9a0b-09a3dc5ae99f
**Figure:** the rank was # 11 on all pages for the first profile; and # 87 for the second profile

🐛 Mobile | Rank is inconsistent after switching profiles

---

src/ApiClient/Services/IActivityFeedService.cs
src/MobileUI/Pages/ActivityPage.xaml
src/MobileUI/ViewModels/ActivityPageViewModel.cs

Closes #843
Fixes a large bottom gap at the end of the collection views on the Activity and finishes up some incomplete work to hook up continuous scrolling by taking advantage of the take/skip parameters of the API.
**❌ Figure: Large gap at bottom of Activity page**
**✅ Figure: Gap no longer present at the bottom of the Activity page. If more items are available they will be loaded as you continue to scroll.**
No

🐛 Mobile | Fix large bottom gap on Activity page and hook up continuous scrolling

---

src/AdminUI/Pages/PrizeDraw.razor
src/ApiClient/Services/IPrizeDrawService.cs
src/Application/PrizeDraw/Queries/GetEligibleUsers.cs
src/Common/DTOs/PrizeDraw/GetEligibleUsersFilter.cs
src/WebAPI/Controllers/LeaderboardController.cs

#533 
- Add a field to `/PrizeDraw` to select Top X users on the Leaderboard
- If the value is 0, is will not be applied.

Filter by leaderboard position

---

src/AdminUI/Pages/DetailedProfile.razor

Closes #527 
Small change to add a warning on profile pages that only the top 3 skills will be displayed in the app.
**Figure: New warning on profile pages in the admin portal**
No

✨ Admin | Add top 3 skills warning

---

src/AdminUI/Shared/MainLayout.razor

A conversation about System Preference Being the Default for Admin Portal. However, we don't have a theme switch in the 2024 design, and should be Dark mode
Update Dark Mode to always be on.
✏️

Force Dark Mode Always

---

src/ApiClient/Services/IUserService.cs
src/Application/Users/Queries/GetSocialMediaId/GetSocialMediaIdQuery.cs
src/Common/DTOs/Users/UserSocialMediaIdDto.cs
src/MobileUI/Controls/SocialMedia.xaml
src/MobileUI/Controls/SocialMedia.xaml.cs
src/MobileUI/Pages/ProfilePages/MyProfilePage.xaml
src/MobileUI/Pages/ProfilePages/MyProfilePage.xaml.cs
src/MobileUI/Pages/ProfilePages/OthersProfilePage.xaml
src/MobileUI/Pages/ProfilePages/OthersProfilePage.xaml.cs
src/MobileUI/Pages/SettingsPage.xaml
src/MobileUI/PopupPages/AddLinkedInPage.xaml
src/MobileUI/PopupPages/AddLinkedInPage.xaml.cs
src/MobileUI/Services/IUserService.cs
src/MobileUI/Services/UserService.cs
src/MobileUI/ViewModels/AddLinkedInViewModel.cs
src/MobileUI/ViewModels/ProfileViewModels/MyProfileViewModel.cs
src/MobileUI/ViewModels/ProfileViewModels/OthersProfileViewModel.cs
src/MobileUI/ViewModels/ProfileViewModels/ProfileViewModelBase.cs
src/WebAPI/Controllers/UserController.cs

✏️ #875
✏️ Added an endpoint and query which returns `SocialMediaId` for a specific user and social media platform. 
Added `SocialMedia` control which displays LinkedIn, GitHub, and Twitter icons. There user can add their LinkedIn profile either via SettingsPage or by tapping the LinkedIn icon.
✏️ No

✨ Mobile | Display LinkedIn icon on ProfilePage

---

src/MobileUI/MauiProgram.cs

🐛 Mobile | Prevent app crash when BackgroundColor is null

---

src/MobileUI/Pages/EarnDetailsPage.xaml
src/MobileUI/Pages/EarnDetailsPage.xaml.cs
src/MobileUI/Resources/Styles/Colors.xaml
src/MobileUI/ViewModels/EarnDetailsViewModel.cs
src/MobileUI/ViewModels/EarnViewModel.cs

Closes #874
1. Sets the default snackbar glyph to a trophy when a quiz is complete as we're not really using the glyphs here.
2. Updates the achievement wording so the text doesn't double the word "quiz".
3. Sets the score background colour to green when passing the quiz.
**Figure: Updated quiz results page with trophy icon, fixed text, and green background colour on the score**
No

♻️ Mobile | Updates to quiz results page

---

src/MobileUI/Controls/MultiLineButton.xaml
src/MobileUI/Controls/MultiLineButton.xaml.cs
src/MobileUI/Controls/Search.xaml
src/MobileUI/MobileUI.csproj
src/MobileUI/PopupPages/ProfilePicturePage.xaml
src/MobileUI/PopupPages/RedeemRewardPage.xaml

Closes #898 
We recently implemented word wrapping on buttons with lots of text, which looks nice and centred on Android but on iOS is left-aligned with no option to adjust. This works around this by implementing a custom multi-line button.
**❌ Figure: Buttons with multi-line text are left-aligned on iOS**
**✅ Figure: Multi-line buttons look nicer now with our custom button**
No

🐛 Mobile | Fix multi-line buttons on iOS

---

src/MobileUI/Controls/MultiLineButton.xaml

Closes #905 
Moving the TouchBehaviour to the parent element of the MultiLineButton so that tapping just the text portion doesn't ignore the tap recognition on the button. This ensures the button works correctly when touching any part of the button on both platforms.
No

🐛Mobile | Fix button not working on Android when text is tapped

---

src/MobileUI/ViewModels/ProfilePictureViewModel.cs

Closes #908 
Permissions.StorageWrite doesn't exist and always returns false on Android SDK 33 and above. This checks for the SDK version and only does this check if it's an older version that still has and requires this.
No

🐛 Mobile | Fix permission check on Android when taking photo

---

src/MobileUI/ViewModels/ActivityPageViewModel.cs
src/MobileUI/ViewModels/ProfileViewModels/ProfileViewModelBase.cs

Related to #782 
The time lapsed values on activity are incorrect as the data is in UTC unlike the methods used. This is a quick fix to update these methods to use UTC and show correct values.
**❌ Figure: The time lapsed values are incorrect and greater than they should be**
**✅ Figure: The values are now correct**
No

🐛 Mobile | Fix incorrect time lapsed for activity

---

src/MobileUI/ViewModels/ProfileViewModels/ProfileViewModelBase.cs

Small bug noticed
Small change to fix an issue where tapping another user's profile pic opens the change profile pic popup.
No.

🐛 Mobile | Don't open profile pic popup when tapping other user's photo

---

src/MobileUI/Pages/NetworkPage.xaml

Closes #915
There's an issue where setting ItemSpacing on CollectionView results in a large gap at the bottom of the collection. We've had to work around this on other pages by removing the spacing and using margins/paddings on the individual items. This brings that fix to the Network page.
**❌ Figure: The Network page has a large gap at the bottom**
**✅ Figure: Gap has been removed**
No

🐛 Mobile | Fix gap at bottom of Network page

---

src/MobileUI/Resources/Styles/Templates.xaml

Closes #918 
Fixes the weird animation when closing the Settings page on iOS by nesting the AvatarView in an outer element that contains the IsVisible flag. Seems like it's an issue with the sizing of the AvatarView when IsVisible is toggled on the element itself.
https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/11418832/0e17c03b-a7b0-4fc7-87ef-adfec7b5187f
**✅ Video: The issue is no longer happening**
No

🐛 Mobile | Fix odd animation when Settings page closed on iOS

---

src/MobileUI/Features/Quiz/QuizDetailsPage.xaml
src/MobileUI/Features/Quiz/QuizDetailsViewModel.cs
src/MobileUI/MauiProgram.cs

Closes #925 
1. Sets the keyboard to "Plain" on the Editor for quizzes to make it easier to input code without autocorrect getting in the way.
2. Replaces special characters like em dashes and curly quotes in the inputted text as the keyboard's Smart Punctuation can insert these and cause issues when code is expected, like in the linked issue.
No

♻️ Mobile | Improve code input when answering quizzes

---

src/Common/DTOs/Leaderboard/LeaderboardUserDto.cs

Testing in TestFlight
We're getting a deserialisation error on LeaderboardUserDto as there's no parameterless constructor. This just adds a parameterless constructor to fix this.
No

🐛 Mobile | Fix leaderboard crash

---

src/MobileUI/Features/Scanner/ScanPage.xaml
src/MobileUI/Features/Scanner/ScanPage.xaml.cs

Part of #948
Newer iPhones have a larger minimum focus distance on the default camera, meaning to scan a QR code the user will need to move their phone farther away to get focus. Apple has example code for handling this (https://developer.apple.com/documentation/avfoundation/capture_setup/avcambarcode_detecting_barcodes_and_faces?language=objc), which involves using the device's MinimumFocusDistance value to calculate the appropriate zoom level required to adequately focus on a subject at a certain percentage of the viewfinder, which is adapted here. Also see code here https://forums.developer.apple.com/forums/thread/715568
Note that the current QR code scanning library is limited …

🐛 Mobile | Improve iOS QR code scanning on newer devices

---

src/MobileUI/Features/Redeem/RedeemRewardPage.xaml
src/MobileUI/Features/Redeem/RedeemRewardPage.xaml.cs
src/MobileUI/Features/Redeem/RedeemRewardViewModel.cs

#968 
Updates the redeem in-person QR code to be larger and to also increase the screen's brightness to make it easier to scan.
**Figure: Redemptions QR code is much larger**
No

♻️ Mobile | Enlarge QR code on redemptions

---

src/MobileUI/Features/AppShell.xaml
src/MobileUI/Features/AppShell.xaml.cs
src/MobileUI/Features/Scanner/ScanPage.xaml.cs

Closes #752
Closes #933
Sets a default top bar icon on navigation to fix the icon being stuck when navigating to certain pages
No

🐛 Mobile | Fix back icon being stuck

---

src/MobileUI/Features/Redeem/RedeemRewardPage.xaml

Closes #952 
Removes a set width on the Confirm button on the shipping modal to fix the text being cut off
**Figure: Confirm button now shows correctly**
No

🐛 Mobile | Fix Confirm button being cut off

---

src/MobileUI/Features/Quiz/QuizDetailsViewModel.cs

Testing the app
Fixes a small bug where if the quiz result check times out it can get stuck as the popup never closes.
Also shortens the timeout.
No

🐛 Mobile | Fix quiz alert not showing and shorten timeout

---

.github/workflows/android-build.yml
.github/workflows/ci.yml
.github/workflows/ios-build.yml
rollback.json

#995 
Creates a rollback.json file to pin the Android SDK to a previous version, as the current one might be causing a crash. See https://github.com/dotnet/android/issues/9039
No

🐛 CI/CD | Pin to Android SDK 34.0.95

---

src/AdminUI/Components/Dialogs/Achievements/AchievementEditDialog.razor

Closes #980 
Adds a Copy Details button to the Achievement Edit modal. Copies the Achievement name and the value of the achievement.
Does NOT copy the Achievement QR Code, as that can already be done by **Right Clicking | Copy Image** 
✏️

Adds a button to copy basic achievement details to clipboard.

---

src/MobileUI/Features/Scanner/ScanPage.xaml
src/MobileUI/Features/Scanner/ScanPage.xaml.cs

Testing
Shows/hides the zoom buttons on the scanner depending on whether the user's device is capable of zoom or not.
Also cleans up the naming of the current scanner view variable.
No

♻️ Mobile | Hide zoom buttons on camera if not zoomable

---

src/MobileUI/Platforms/iOS/Info.plist

Closes #1014 
Updates the info.plist with the bundle name "SSW Rewards" so the auth popup no longer shows "MobileUI" 
**✅ Figure: Popup now shows "SSW Rewards"**
No

🐛 Mobile | Show correct bundle name on iOS

---

src/MobileUI/Features/Quiz/QuizViewModel.cs
src/MobileUI/Features/Redeem/RedeemViewModel.cs

Closes #1016 
Updates ObservableCollection to ObservableRangeCollection on the carousel pages as updating the data on the carousel can cause it to crash in certain instances - particularly when the list is cleared and new items are being added when the carousel position might be changing. This also improves performance on these pages when reloading as the lists don't trigger change detection on every item added, and just updates in one hit.
No

🐛 Mobile | Fix crash on carousels

---

src/Application/ActivityFeed/Queries/GetActivitiesQuery.cs
src/Application/Network/Queries/GetNetworkProfileList/GetNetworkProfileListQuery.cs

Closes #1026
Currently the Network tab is returning incorrect data and crashing when tapping a user as the user ID isn't returned.
This fixes those issues by updating the query and making sure the ID is returned. Also fixes the Activity feed to use the correct Friends feed.
No

🐛 API | Fix network query

---

src/MobileUI/Platforms/Android/MainActivity.cs

Closes #734 
Sets LaunchMode = SingleTop to fix an issue where the app could sometimes crash on Android when reopened from the background.
No

🐛 Mobile | Change LaunchMode to SingleTop to fix "Window was already created" issue

---

src/MobileUI/Features/Activity/ActivityPageViewModel.cs
src/MobileUI/Features/Leaderboard/LeaderboardViewModel.cs

Testing
Moves all ObservableCollections annotated with [ObservableProperty] to ObservableRangeCollection for better, more optimised collection handling.
Fixes up some of the handling on the activity page.
No

♻️ Mobile | Move ObservableCollections to ObservableRangeCollection

---

src/MobileUI/Features/OnBoarding/OnBoardingViewModel.cs

Closes #1029 
Updates the intro screens as per Seth's email.
**Figure: Page 2 updated with new text and swapped with page 3**
**Figure: Page 3 updated with new text and swapped with page 2**
**Figure: Page 4 updated with new text**
**Figure: Page 5 updated with new text**
No

♻️ Mobile | Update onboarding screens

---

src/MobileUI/Features/Flyout/FlyoutHeader.xaml

Closes #1032 
Increases the font size of the total points in the flyout to stand out.
**Figure: Text size is increased**
No

♻️ Mobile | Increase text size of total points

---

src/MobileUI/Features/BaseViewModel.cs
src/MobileUI/Features/Redeem/RedeemRewardPage.xaml
src/MobileUI/Features/Redeem/RedeemRewardPage.xaml.cs
src/MobileUI/Features/Redeem/RedeemRewardViewModel.cs

Closes #1027 
Increases the size of prizes images when a user tries to redeem it.
Also helps make redeeming in-person less confusing by adding a "confirm redeemed" button which the user can tap to close the window once the QR code has been scanned, so they shouldn't try cancelling.
**Figure: Image size is much larger and easier to see**
**Figure: Users should be less confused about the cancel button after getting their code scanned**
No

✨ Mobile | Increase prize image size

---

README.md

✏️ Email: SSW Intranet - Roadmap Links
✏️ Add vision and features
✏️ No

Add vision and features to remove from internal projects

---

.github/workflows/admin-build.yml
.github/workflows/admin-deploy.yml
.github/workflows/android-build.yml
.github/workflows/android-deploy.yml
.github/workflows/api-az-deploy.yml
.github/workflows/api-build.yml
.github/workflows/az-deploy.yml
.github/workflows/ios-build.yml
.github/workflows/ios-deploy.yml

Failing workflows due to actions/upload-artifact and actions/download-artifact being deprecated.
Updates actions/upload-artifact and actions/download-artifact to the latest v4
No

♻️ CI/CD | Update actions/upload-artifact and  actions/download-artifact to v4

---

src/AdminUI/Components/AdminQRCode.razor
src/MobileUI/Common/ImageHelpers.cs
src/MobileUI/Features/App.xaml.cs
src/MobileUI/Features/Login/LoginPage.xaml.cs
src/MobileUI/Features/Login/LoginPageViewModel.cs
src/MobileUI/MauiProgram.cs
src/MobileUI/Platforms/Android/MainActivity.cs
src/MobileUI/Platforms/iOS/Info.plist
src/MobileUI/Services/AuthenticationService.cs
src/MobileUI/Services/ScannerService.cs

Closes #321
1. Adds an "sswrewards://" custom URL scheme to allow invoking and communicating with the app directly.
2. Handles receiving QR codes via a link in the format of "sswrewards://redeem?code={{code}}".
3. Prepends this new URL scheme when rendering existing codes
No

✨ Mobile | Add deep linking

---

src/Common/DTOs/Quizzes/QuestionResultDto.cs
src/MobileUI/Common/Messages/TopBarAvatarMessage.cs
src/MobileUI/Features/Quiz/QuizDetailsPage.xaml
src/MobileUI/Features/Quiz/QuizDetailsViewModel.cs
src/MobileUI/Features/TopBar/TopBarViewModel.cs
src/MobileUI/Resources/Styles/Colors.xaml
src/MobileUI/Resources/Styles/Templates.xaml

Closes #844 
Updates the quiz results page to use Ken's design.
**✅ Figure: Quiz results page when test passed**
**✅ Figure: Quiz results page when test failed**
No

✨ Mobile | Update quiz results design

---

src/MobileUI/Features/Flyout/FlyoutHeader.xaml

Closes #1049 
Implements Ken's design for the stats section of the flyout.
**✅ Figure: Improved stats section in the flyout**
No

✨ Mobile | Update design of user stats in the flyout

---

.github/workflows/admin-build.yml
.github/workflows/android-build.yml
.github/workflows/api-build.yml
.github/workflows/ci.yml
.github/workflows/ios-build.yml
.github/workflows/ios-deploy.yml
global.json

Failing build and deploy for iOS
It seems that some change in the build pipeline has caused iOS builds to fail recently. Pinning the dotnet version to 8.0.402 and using macos-14 in the build seems to be a common workaround, so giving this a go here.
See: https://developercommunity.visualstudio.com/t/iOS-MAUI-The-type-UIKitNSAdaptiveImage/10754377
No

🛠️ Fix iOS build in pipeline

---

src/MobileUI/Features/SocialMedia/AddSocialMediaViewModel.cs

Conversation with Seth
Small fix to the LinkedIn validation regex as it doesn't match the placeholder text, which includes "www". This updates the patterns to allow both www and http on all URLs.
No

🐛 Mobile | Fix LinkedIn regex

---

src/MobileUI/Resources/Styles/Templates.xaml

Closes #1079
On new iPhone models such as the iPhone 16 Pro Max the top bar is displayed with a gap. This removes the gap to make it more consistent across devices.
**✅ Figure: Top bar now displaying correctly on iPhone 16 Pro Max**
For reference, this also remains consistent across other devices:
**✅ Figure: Pixel 7**
**✅ Figure: iPhone SE**
**✅ Figure: iPhone 15 Pro Max**
No

🐛 Mobile | Fix top bar alignment on newer iPhones

---

.github/workflows/android-build.yml
rollback.json
src/MobileUI/MobileUI.csproj

Failing Android build in pipeline
We had set a rollback file to pin to a specific Android SDK as we were getting HttpClient disposed crashes. This is now clashing with global.json and causing the Android build to fail in the pipeline. See here for the issue: https://github.com/dotnet/android/issues/9039
It appears the issue still persists on newer versions, however a workaround is to disable the native HTTP handler. This seems to all work okay for me locally.
This PR removes the rollback file and disables the native HTTP handler on Android in the .csproj file.
No

🛠️ Fix Android build in pipeline

---

src/MobileUI/Features/App.xaml.cs

Closes #1084 
It seems on Android the login callback triggers the OnAppLinkRequestReceived method that we're using to capture links using our custom URL scheme. This updates this method to check for the correct URL scheme and only execute if it matches our own.
No

🐛 Mobile | Fix code unrecognised popup on first login on Android

---

src/MobileUI/Features/Profile/ProfileViewModelBase.cs
src/MobileUI/Features/Settings/SettingsViewModel.cs
src/MobileUI/Features/SocialMedia/AddSocialMediaPage.xaml
src/MobileUI/Features/SocialMedia/AddSocialMediaPage.xaml.cs
src/MobileUI/Features/SocialMedia/AddSocialMediaViewModel.cs

Closes #1087 
1. Fixes setting the cursor position to the end when tapping the field in the social media popup.
2. Updates the social media popups to load existing data when opened from the Settings page.
**✅ Figure: Social media popups now show existing data**
No

🐛 Mobile | Social media fixes

---

src/MobileUI/Features/AppShell.xaml.cs
src/MobileUI/Resources/Styles/Templates.xaml

Testing
1. Implements a proper workaround on iOS for the gap that appears above our custom top bar. We previously worked around this by setting a negative Y translation on the top bar on iOS but this gap can change between devices (such as the latest iPhone 16 models which have an increased gap). This change fills the gap with our Background colour for all gap sizes so our top bar template can work generically.
2. Fixes an issue where title text in the top bar can be off-centre.
**✅ Figure: There are no gaps above the top bar when the Y translation is removed**
**✅ Figure: Title text is now correctly vertically centred**
No

🐛 Mobile | Top Bar fixes

---

src/Application/Achievements/Command/PostAchievement/PostAchievementCommand.cs

Crashes
Crashes might be related to achievements returning an incorrect UserID. Disabling for the time being which should hopefully prevent the app from trying to fetch the user.
No

🐛 Bug | Temporarily disable returning UserId with achievements

---

src/MobileUI/Features/AboutSSW/AboutSswPage.xaml.cs
src/MobileUI/Features/Profile/ProfileViewModelBase.cs

Closes #1062
There's currently an issue with MAUI on Android 14 when using BrowserLaunchMode.External where a FeatureNotSupportedException can be thrown. This change wraps these in a try...catch to handle this a bit more gracefully for the time being.
No

🐛 Mobile | Add try...catch when launching external browser

---

src/Application/Leaderboard/Queries/GetFilteredLeaderboardList/GetFilteredLeaderboardList.cs
src/Application/Leaderboard/Queries/GetFilteredLeaderboardList/GetFilteredLeaderboardListQuery.cs
src/Application/Leaderboard/Queries/GetLeaderboardList/GetLeaderboardListQuery.cs
src/Application/PrizeDraw/Queries/GetEligibleUsers.cs
src/Application/PrizeDraw/Queries/Mapping.cs
src/Common/DTOs/Leaderboard/LeaderboardUserDto.cs

Closes #1108 
Updates the weekly leaderboard to use the last 7 days rather than the current week.
No

♻️ API | Update weekly leaderboard to use past 7 days

---

src/Application/Common/Behaviours/LoggingBehaviour.cs
src/Application/Common/Behaviours/PerformanceBehaviour.cs
src/Application/Services/UserService.cs

✏️ #1119 
✏️ PerformanceBehaviour no longer uses a super heavy method on requests that takes 500+ ms.  that even on powerful machine takes ~350 ms.
Also, `GetUserId` was optimised to only return id instead of entire row which should further improve performance for many endpoints.
✏️ No.

⚡ Improved performance for logging when any request takes 500ms+

---

src/Application/Achievements/Command/PostAchievement/PostAchievementCommand.cs
src/Application/Common/Interfaces/IUserService.cs
src/Application/Notifications/Commands/RequestNotification/RequestNotification.cs
src/Application/Notifications/Commands/RequestNotification/RequestNotificationCommand.cs
src/Application/Services/UserService.cs
src/Application/Staff/Queries/GetStaffList/GetStaffListQuery.cs

✏️ #1119 
✏️ When code needed just `CurrentUserId` it used the entire user table with achievements and rewards. This will only fetch the bare minimum not only to return the `CurrentUserId` but also activate the user if needed.
Impacts several endpoints like posting achievements, requesting notifications and getting staff list.
✏️ No.

⚡ Only fetch UserId when needed instead of entire row

---

.github/workflows/api-main.yml

Fixing GitHub Actions
Replaced
Azure_Credentials secrets with
AZURE_CLIENT_ID
AZURE_TENANT_ID 
AZURE_SUBSCRIPTION_ID
Zendesk Ticket  https://pdi-ssw.zendesk.com/agent/tickets/15652
The api-main.yml file
Similar change to https://github.com/SSWConsulting/SSW.Rewards.Mobile/pull/1122/files
https://learn.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=openid%2Cpython%2Caspnetcore
I worked with @chrisschultzssw @kikibianc @jernejk @vladislav-kir

Admin | Changing Azure auth to federated credentials

---

src/Application/Common/Interfaces/ICurrentUserService.cs
src/Application/Common/Interfaces/IUserService.cs
src/Application/Network/Queries/GetNetworkProfileList/GetNetworkProfileListQuery.cs
src/Application/Services/UserService.cs
src/Application/Staff/Queries/GetStaffList/GetStaffListQuery.cs
src/Application/Users/Queries/GetCurrentUserRoles/GetCurrentUserRolesQuery.cs
src/Common/DTOs/Users/UserProfileDto.cs
src/WebAPI/Services/CurrentUserService.cs

✏️ #1119
Get /api/user/GetUser/{id}, /api/staff/get and /api/network/GetList were one of most expensive endpoint relative to usage at NDC Porto.
✏️ Optimised queries and minor refactors.
On my desktop when testing 10 concurrent connection for 1 minute, I've seen about double the performance from ~10 to ~20 req/s.
✏️ No.

⚡ Improvement performance for getting user by ID and list of staff members

---

src/Application/Achievements/Command/ClaimAchievementForUser/ClaimAchievementForUserCommand.cs
src/Application/Achievements/Command/ClaimFormCompletedAchievement/ClaimFormCompletedAchievementCommand.cs
src/Application/Achievements/Command/ClaimSocialMediaAchievementForUser/ClaimSocialMediaAchievementForUserCommand.cs
src/Application/Achievements/Command/PostAchievement/PostAchievementCommand.cs
src/Application/Achievements/Command/UpdateAchievement/UpdateAchievementCommand.cs
src/Application/Common/Constants/CacheKeys.cs
src/Application/Common/Interfaces/ICacheService.cs
src/Application/Common/Options/CacheOptions.cs
src/Application/GlobalUsings.cs
src/Application/Leaderboard/Queries/GetLeaderboardList/GetLeaderboardListQuery.cs
src/Application/Rewards/Commands/ClaimReward/ClaimRewardCommand.cs
src/Application/Rewards/Commands/ClaimRewardForUser/ClaimRewardForUserCommand.cs
src/Application/Rewards/Commands/DeleteReward/DeleteRewardCommand.cs
src/Application/Rewards/Commands/UpdateReward/UpdateRewardCommand.cs
src/Application/Services/UserService.cs
src/Common/DTOs/Users/UserRankingMinimumDto.cs
src/Infrastructure/ConfigureServices.cs
src/Infrastructure/SSW.Rewards.Infrastructure.csproj
src/Infrastructure/Services/CacheService.cs
src/WebAPI/appsettings.json

✏️ #1152 
✏️ Added `ICachingService`, `CacheKeys` and `CacheTags` to create and manage caches.
✏️ No.

✨ Add caching service and cached leaderboard, and user rankings

---

src/Application/Network/Queries/GetNetworkProfileList/GetNetworkProfileListQuery.cs
src/Common/DTOs/Network/NetworkProfileDto.cs
src/Domain/Entities/StaffMember.cs

✏️ #1171 
For some reason, some scanned users were omitted and the endpoint is one of the slowest query endpoints that happen frequently.
✏️ Rewrote all queries related to the endpoint, added lots of comments and hopefully the code is now easier to understand to maintain.
Also, originally it sorted and ranked by `AllPoints` which was 0 for everyone, now it sorts and ranks by users' Value. (for instance Adam has 1000 value and is rank 1)
✏️ Reviewed by @vladislav-kir a few times and ChatGPT to verify if I missed anything (old code was 4/10 and new code is rated 9/10 with suggestion not worth implementing).
**Figure: Production speed of old …

1171 network list scanned list not correct

---

src/Application/Achievements/Queries/SearchAchievements/SearchAchievementQuery.cs

✏️ #1173 
✏️ When search term is empty, it will no longer crash.
✏️ No.

🐛 Fixed a bug that cause /api/achievement/search to crash.

---

src/MobileUI/Features/Scanner/ScanViewModel.cs

✏️ #1176 
✏️ When scanning for QR code, it only reacts to QR codes that starts with "sswrewards://". Other QR codes are ignored.
✏️ No.

✨ Reacts only to QR codes that contains "sswrewards://"

---

src/Application/Achievements/Queries/SearchAchievements/SearchAchievementQuery.cs
src/Application/Common/Extensions/EfCoreLinqExtensions.cs
src/Application/Common/Interfaces/IPagedRequest.cs
src/Application/Rewards/Queries/SearchRewards/SearchRewardsQuery.cs
src/WebAPI/Controllers/AchievementController.cs
src/WebAPI/Controllers/RewardController.cs

…lts when query is empty
✏️ #1173 
✏️ Fixed crash for rewards and rewards/achievements search now return results when query string is null/empty.
It also now does pagination by default (default 50 items)
✏️ No.

🐛 Fix crashing and not returning results for achievements and rewards search

---

src/AdminUI/Components/AdminQRCode.razor
src/AdminUI/GlobalUsings.cs
src/ApiClient/Constants.cs
src/MobileUI/Common/ImageHelpers.cs
src/MobileUI/Config/ScannerConfig.cs
src/MobileUI/DependencyInjection.cs
src/MobileUI/Features/Scanner/ScanResponseViewModel.cs
src/MobileUI/Features/Scanner/ScanResultViewModel.cs
src/MobileUI/Features/Scanner/ScanViewModel.cs
src/MobileUI/GlobalUsings.cs
src/MobileUI/Platforms/Android/AndroidManifest.xml
src/MobileUI/Platforms/iOS/Info.plist
src/MobileUI/Services/ScannerService.cs

✏️ #1181 
✏️ Improved QR code scanning. Not only it supports old QR codes (with just base64 that have "ach:", "rwd:", etc. in the body) but also now checks which of the visible QR codes are valid. This means that if there is 1 SSW Rewards QR Code and 9 random QR Codes, it will always pick SSW Rewards QR Code.
✏️ No.

🐛 Re-added support for older QR Codes, improved QR scanning logic and bumped mobile version

---

src/ApiClient/Constants.cs
src/MobileUI/Features/Scanner/ScanViewModel.cs
src/MobileUI/Platforms/Android/AndroidManifest.xml
src/MobileUI/Platforms/iOS/Info.plist
src/MobileUI/Services/ScannerService.cs

✏️ #1181 
✏️ It appears that ApiClient project didn't rebuild when I made a small change and resulted in malformed URL.
✏️ No.

🐛 Updated a constant that didn't seem to refresh when doing final testing

---

src/MobileUI/Features/App.xaml.cs
src/MobileUI/MauiProgram.cs
src/MobileUI/Platforms/Android/AndroidManifest.xml
src/MobileUI/Platforms/iOS/Info.plist

✏️ #1181 - When testing QR Codes with full URL, it was crashing on Android if the app was closed or suspended.
✏️ Removed `activity.Finish()`.
✏️ No.

🐛 Fix Android crash when accepting URL from camera

---

.github/workflows/ios-build.yml
src/Application/Achievements/Command/CreateAchievement/CreateAchievementCommand.cs
src/Application/Common/Extensions/UserExtensions.cs
src/Application/Common/Helpers/AchievementHelper.cs
src/Application/Services/UserService.cs
src/Application/Staff/Commands/UpsertStaffMemberProfile/UpsertStaffMemberProfileCommand.cs
src/Application/System/Commands/Common/SampleDataSeeder.cs

https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/1150
- UserService | CreateUser - Automatically create a Staff record for new Staff users
- UpsertStaffMemberProfileCommandHandler - Automatically create a User record for new Staff records
- Added AchievementHelper | GenerateCode - refactored repeated code for generating Achievement QR Code
No

1150 - Fix crash when clicking on Staff without User record

---

src/MobileUI/Features/Login/LoginPageViewModel.cs
src/MobileUI/Features/Quiz/QuizDetailsViewModel.cs
src/MobileUI/Features/Redeem/RedeemRewardViewModel.cs
src/MobileUI/MauiExceptions.cs
src/MobileUI/MauiProgram.cs
src/MobileUI/MobileUI.csproj
src/MobileUI/Platforms/Android/AndroidManifest.xml
src/MobileUI/Platforms/Android/MainActivity.cs
src/MobileUI/Platforms/Android/Resources/values/strings.xml
src/MobileUI/Platforms/iOS/AppDelegate.cs
src/MobileUI/Platforms/iOS/Entitlements.plist
src/MobileUI/Platforms/iOS/Info.plist
src/MobileUI/Services/AuthenticationService.cs
src/MobileUI/Services/FirebaseAnalyticsService.cs
src/MobileUI/Services/PushNotificationsService.cs

AppCenter is retiring and needs to be replaced.
Closes #868 
- Replaces the deprecated Xamarin.Firebase.* packages with the newer and maintained Plugin.Firebase.* packages.
- Sets up Crashlytics from the Plugin.Firebase library and updates the global exception handling to report to Firebase.
- Updates the existing CloudMessaging integration for Android with the new Plugin.Firebase and sets up preliminary support for iOS notifications.
No

♻️ Mobile | Set up Firebase exception handling

---

.github/workflows/ios-build.yml

Failing iOS build in pipeline
The pipeline is now complaining about the SDK version being too old. This bumps it up to the latest to hopefully resolve this.
No

Bump Xcode version in pipeline

---

.github/workflows/mobile-main.yml

We're getting this error on the Android deploy:
"Error: Version code 1 has already been used."
This is being set by the "Generate build number" step in the workflow. This seems to be working correctly, but the output seems to generate an integer greater than the 32-bit max, which is what the Android build expects. This might be why it's being recorded as "1" here.
This updates the build number to instead be generated by the count of commits on the branch, which provides a more sane number that auto-increments with every push to main.

Set build version from count of commits

---

.github/workflows/mobile-main.yml

My last PR wasn't working as expected as it seems by default the repo doesn't return the full history (so it only shows 1). This should hopefully set the build correctly as it should see the full history.

Fix build number setting in workflow

---

.github/workflows/android-build.yml

One more go at trying to resolve this before I give up 😅
Sets the ApplicationVersion on the publish command to hopefully fix it being set to 1 in the pipeline. I can confirm that this command works locally to set it on the resulting APK/AAB.

Set ApplicationVersion on the publish command in pipeline

---

src/MobileUI/MobileUI.csproj

The publish build for iOS in the pipeline is currently taking forever (50-60 minutes) compared to the Android build (10 or so minutes).
This tweak should speed up the iOS build.

Speed up iOS publish build in pipeline

---

src/Application/Leaderboard/Queries/GetLeaderboardList/GetLeaderboardListQuery.cs
src/Application/Network/Queries/GetNetworkProfileList/GetNetworkProfileListQuery.cs

Users that don't have a Profile Picture in blob storage sometimes get incorrect picture, instead of the local v2sophie.png
closes #1154 
Leaderboard & Network Queries - if User has no Profile Picture - use v2sophie.png from blob storage 
No

Leaderboard & Network pages - fix incorrect user profile pictures

---

src/MobileUI/Features/SocialMedia/AddSocialMediaPage.xaml
src/MobileUI/Features/SocialMedia/AddSocialMediaViewModel.cs

Closes #1213
1. Updates the social media popup to insert existing links as text rather than a placeholder so it doesn't show an error about the field being empty when the Connect button is tapped and nothing was changed.
2. Shows "✅ Done" when Connect is tapped and the field is valid.
3. Adds an icon for the selected social media below the field that can be tapped to open the entered URL.
**FIgure: Updated social media popup with no more placeholder text and new tappable icon**
No

🐛 Mobile | Fix error messages on social media popup

---

src/MobileUI/Controls/CustomTabBar.cs
src/MobileUI/Controls/ProfileStats.xaml
src/MobileUI/Features/Activity/ActivityPage.xaml
src/MobileUI/Features/Activity/ActivityPageViewModel.cs
src/MobileUI/Features/AppShell.xaml
src/MobileUI/Features/AppShell.xaml.cs
src/MobileUI/Features/Profile/MyProfilePage.xaml
src/MobileUI/Features/Profile/OthersProfilePage.xaml
src/MobileUI/Features/Quiz/QuizViewModel.cs
src/MobileUI/Features/Redeem/RedeemPage.xaml
src/MobileUI/Features/Redeem/RedeemViewModel.cs
src/MobileUI/Features/Scanner/ScanViewModel.cs
src/MobileUI/Features/TopBar/TopBarViewModel.cs
src/MobileUI/MauiProgram.cs
src/MobileUI/Platforms/Android/Renderers/CustomShellHandler.cs
src/MobileUI/Platforms/Android/Renderers/CustomShellItemRenderer.cs
src/MobileUI/Platforms/Android/Renderers/CustomShellSectionRenderer.cs
src/MobileUI/Platforms/iOS/Renderers/CustomShellHandler.cs
src/MobileUI/Platforms/iOS/Renderers/CustomShellItemRenderer.cs
src/MobileUI/Resources/Styles/Templates.xaml

Closes #1214 
1. Rearranges the tab bar and uses custom platform code to allow a big centre button for scanning.
2. Adds the SSW logo at the top.
3. Moves activity to the top right and makes it a pop up as it's no longer a shell page.
4. Tweaks the close button on other popups for consistency with the new activity popup.
5. Adds an override so iPads on iPadOS 18 use our custom tab bar and not the new default one at the top of the screen.
**Figure: Icons now rearranged with a big scan button in the center**
No

♻️ Mobile | Update tab bar design

---

src/MobileUI/Platforms/iOS/Renderers/CustomShellHandler.cs
src/MobileUI/Platforms/iOS/Renderers/CustomShellPageRendererTracker.cs

While testing on very rare occasions the iOS app can crash while navigating. This is a MAUI bug that should hopefully be fixed in .NET 9.
Overrides a shell page handler to add a null check to fix this issue.
No

🐛 Mobile | iOS crash fix

---

src/MobileUI/Features/AboutSSW/AboutSswPage.xaml
src/MobileUI/Features/OnBoarding/OnBoardingPage.xaml
src/MobileUI/Features/Profile/ProfilePicturePage.xaml
src/MobileUI/Features/Redeem/RedeemRewardPage.xaml
src/MobileUI/Features/SocialMedia/AddSocialMediaPage.xaml

Closes #1113
Fixes status bar colour mismatch when opening popups on iOS by setting it to transparent.
https://github.com/user-attachments/assets/3821d4b6-aba1-4cc1-9b3c-ee6a0b762f1a
**✅ Figure: Popups on iOS now longer show a mismatched status bar colour**
No

🐛 Mobile | Fix popups changing status bar colour on iOS

---

src/MobileUI/DependencyInjection.cs
src/MobileUI/Features/Activity/ActivityPageViewModel.cs
src/MobileUI/Features/AppShell.xaml.cs
src/MobileUI/Features/Flyout/FlyoutFooterViewModel.cs
src/MobileUI/Features/Leaderboard/LeaderboardViewModel.cs
src/MobileUI/Features/Network/NetworkPageViewModel.cs
src/MobileUI/Features/Profile/OthersProfilePage.xaml.cs
src/MobileUI/Features/Quiz/QuizDetailsPage.xaml.cs
src/MobileUI/Features/Quiz/QuizViewModel.cs
src/MobileUI/Features/Scanner/ScanResultViewModel.cs
src/MobileUI/Features/Settings/SettingsViewModel.cs
src/MobileUI/Features/TopBar/TopBarViewModel.cs
src/MobileUI/MobileUI.csproj

Testing
There's an issue with MAUI where navigating between different non-tabbed pages can cause a crash due to the routing using existing navigation stacks between tabs. This works around this by moving away from routing for pages that aren't a part of the Shell tabs and instead instantiating them and pushing them to the stack so the routing can't get them confused with other navigation stacks.
No

🐛 Mobile | Fix rare navigation crash

---

src/MobileUI/Features/Leaderboard/LeaderboardPage.xaml
src/MobileUI/Features/Leaderboard/LeaderboardPage.xaml.cs
src/MobileUI/Platforms/iOS/Renderers/CustomShellItemRenderer.cs

Testing
Fixes a couple iPad issues:
1. The podium on the leaderboard page doesn't resize when the window size changes.
2. The scan button gets misaligned when the window size changes.
No

🐛 Mobile | Fix iPad layout issues

---

src/ApiClient/Services/ILeaderboardService.cs
src/Application/Leaderboard/Queries/GetLeaderboardList/GetLeaderboardListQuery.cs
src/Application/Leaderboard/Queries/GetLeaderboardPaginatedList/GetLeaderboardPaginatedListQuery.cs
src/MobileUI/Features/Leaderboard/LeaderboardPage.xaml
src/MobileUI/Features/Leaderboard/LeaderboardViewModel.cs
src/MobileUI/Services/LeaderService.cs
src/WebAPI/Controllers/LeaderboardController.cs

https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/1242
- API - Added /Leaderboard/GetPaginated endpoint so the changes do not affect Admin portal
- Mobile App - Leaderboard now incrementally loads 50 users at a time.
No

Mobile App - Leaderboard incremental load by 50 users

---

src/MobileUI/Platforms/Android/AndroidManifest.xml

Crashing when scanning QR code with Android phone
Fix crash on android when scanning QR Code - Add VIBRATE permission to AndroidManifest
No

Mobile App - Android - Fix crash on QR code scanning

---

src/MobileUI/Features/Leaderboard/LeaderboardViewModel.cs

Issues encountered after https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/1242 deployment
fix racing condition that results in duplicates on initial load - stop LoadMore method if the initial load is not complete
✏️

Mobile app - Leaderboard - Incremental load duplicates fix

---

src/ApiClient/Services/IAchievementAdminService.cs
src/Application/Achievements/Command/CreateAchievement/CreateAchievementCommand.cs
src/Application/Common/Extensions/UserExtensions.cs
src/Application/Common/Helpers/AchievementHelper.cs
src/Application/Services/UserService.cs
src/Application/Staff/Commands/UpsertStaffMemberProfile/UpsertStaffMemberProfileCommand.cs
src/Application/System/Commands/Common/SampleDataSeeder.cs

Related to #1269
Looking into #1269 I noticed that there are two "Eli Kent" achievements in the database. I haven't yet worked out how this could have happened in the first place, but this raises an issue in that we can have duplicate achievements sharing the same code, meaning a user scanning that code will just claim whatever is fetched first from the db.
There's no real need to use the user's name in the code itself, so this updates future staff profile achievements to simply use a GUID so we don't run into duplicate codes going forward.
No

♻️ Mobile | Use GUIDs for staff achievements to prevent duplicates

---

src/MobileUI/Features/Redeem/RedeemViewModel.cs
src/MobileUI/Models/Reward.cs

Closes #1261
Makes CanAfford observable and updates this when balance changes so that the state of the redeem buttons can always be in sync with the balance.
No

♻️ Mobile | Update redeem button state on balance change

---

src/Application/Leaderboard/LeaderboardService.cs
src/Application/Leaderboard/Queries/GetLeaderboardList/GetLeaderboardListQuery.cs
src/Application/Leaderboard/Queries/GetLeaderboardPaginatedList/GetLeaderboardPaginatedListQuery.cs
src/Application/Services/UserService.cs
src/Common/DTOs/Users/CurrentUserDto.cs
src/Infrastructure/ConfigureServices.cs
src/MobileUI/Features/Leaderboard/LeaderboardPage.xaml
src/MobileUI/Features/Leaderboard/LeaderboardPage.xaml.cs
src/MobileUI/Features/Leaderboard/LeaderboardViewModel.cs
src/MobileUI/Services/LeaderService.cs
src/MobileUI/Services/UserService.cs
src/WebAPI/Controllers/LeaderboardController.cs

Closes #1242
- Improves performance of the paginated leaderboard endpoint and updates the mobile app to properly use this.
- Simplifies LeaderboardViewModel a fair bit.
- Now retrieves the current user's ranking from the current user profile rather than a side effect in the leaderboard.
@jernejk started the work on this.

♻️ Mobile/API | Add paginated loading to leaderboard

---

src/MobileUI/Features/Leaderboard/LeaderboardViewModel.cs

Testing
Tiny change to fix an issue on iOS where pull-to-refresh results in the top part of the podium being cut off. Seems it's an issue with the loading circle interfering with the layout of the podium, but unsure why. This small change fixes the issue while still maintaining the same appearance.
No

🐛 Mobile | Fix pull-to-refresh cutting off podium on iOS

---

src/AdminUI/AdminUI.csproj
src/AdminUI/Helpers/NavigationPages.cs
src/AdminUI/Pages/KioskLeaderboard.razor
src/AdminUI/Shared/KioskLayout.razor
src/AdminUI/Shared/KioskLayout.razor.css
src/AdminUI/Shared/NavMenu.razor
src/ApiClient/Services/ILeaderboardService.cs
src/Application/Common/Extensions/PaginationResultExtensions.cs
src/Application/Leaderboard/Queries/GetKioskLeaderbaoard/GetMobileLeaderbaoard.cs
src/Application/Leaderboard/Queries/GetLeaderboardPaginatedList/GetLeaderboardPaginatedListQuery.cs
src/Common/DTOs/Leaderboard/LeaderboardUserDto.cs
src/Common/DTOs/Leaderboard/MobileLeaderboardViewModel.cs
src/Common/DTOs/Pagination/IPaginationResult.cs
src/WebAPI/Controllers/LeaderboardController.cs

✏️  By #1267 for NDC Porto next week.
✏️ Added new kiosk leaderboard mode and new mobile-centric leaderboard endpoints.
The new `/api/Leaderboard/GetKioskPaginated` reduces the size of the leaderboard significantly which can be essential when conference WiFi is starting to drop.
| Endpoint | 10 users / size | 10 users @ 50kB/s | 50 users | 50 users @ 50kB/s |
| ------------------------------------------ | --------- | ------- | --------- | ------- |
| /api/Leaderboard/Get                            | 400+kB | 8+ sec | 400+kB | 8+ sec |
| /api/Leaderboard/GetPaginated            | 3.2kB    | 64 ms   | 16kB     | 320 ms |
| /api/Leaderboard/GetMobilePaginated | 1.7kB    | 34 ms   | …

✨ Add leaderboard Kiosk Mode

---

src/Application/Leaderboard/Queries/GetMobileLeaderbaoard/GetMobileLeaderbaoard.cs
src/WebAPI/Controllers/LeaderboardController.cs

✏️ To fix a bug for #1267 
✏️ Points for kiosk leaderboard for "All Time" is now correct.
✏️ No.

🐛 Fixed /api/Leaderboard/GetMobilePaginated not showing correct points

---

src/MobileUI/MobileUI.csproj
src/MobileUI/Platforms/Android/Renderers/CustomShellItemRenderer.cs
src/MobileUI/Platforms/iOS/Renderers/CustomShellItemRenderer.cs

Testing
There's an issue on Android where the scan button can appear different on different devices due to variations of pixel densities. This updates the button rendering to take screen density into account so it appears the same across devices.
Also cleans up the code, along with the iOS counterpart.
**❌ Figure: Button appears too large on low-dpi display**
**✅ Figure: Button now consistent across densities**
No

🐛 Mobile | Fix Android scan button inconsistencies

---

src/MobileUI/Common/ExceptionHelper.cs
src/MobileUI/Features/App.xaml.cs
src/MobileUI/Features/Flyout/FlyoutFooterViewModel.cs
src/MobileUI/Features/Settings/DeleteProfilePage.xaml.cs
src/MobileUI/MobileUI.csproj
src/MobileUI/Services/AuthenticationService.cs

Closes #1295
There's a bug where if you sign out, on Android you can tap the back button and it will close the login page and allow you to interact with the app as normal. This is due to the previous behaviour simply pushing the login page as a modal on top of the current navigation stack. This change fixes that by replacing MainPage entirely by LoginPage whenever we're signing out.
Note: MainPage is being deprecated in .NET 9 so this will need to change again, but this should solve the issue for the time being.
No

🐛 Mobile (Android) | Fix being able to navigate back after logout

---

src/MobileUI/Controls/ListItem.xaml

Closes #1303 #1296
It seems the slowness on the Redeem page (particularly on Android) is due to very large thumbnails being uploaded for these prizes. The current prizes seem to be using the same image sizes for both the main image and the thumbnails when they shouldn't be (perhaps we could implement something in the future to auto generate thumbnails?).
Setting a WidthRequest and HeightRequest on the image works around this by not trying to render the full size and improves performance significantly. But we should still update the thumbnails in the Admin portal so we're not serving these full size images when we don't need to be.
No

♻️ Mobile | Improve performance of Redeem page

---

src/Application/Services/UserService.cs

Testing/bug reports
Clears the cache for rankings and leaderboard when a user is activated as the activation flag affects the rankings in GenerateRanking(). This may be causing crashes for newly created users as they could be trying to get their ranking from a cached list where they don't exist due to their user not being activated yet in the cache.
No

♻️ API | Clear rankings cache on activation

---

src/MobileUI/Features/Scanner/ScanViewModel.cs
src/MobileUI/MobileUI.csproj

Testing
There's a bug in the version of the barcode scanning library we're using where the scanner can crash if the user has manually disabled camera permissions in settings. This only seems reproducible on physical devices (simulator works okay).
This bug was fixesdin a later version (see https://github.com/afriscic/BarcodeScanning.Native.Maui/issues/133) so this PR bumps this version along with some other conflicting packages.
No

🐛 Mobile | Fix crash when camera permissions disabled

---

src/AdminUI/AdminUI.csproj
src/AdminUI/Pages/PrizeDraw.razor
src/AdminUI/Program.cs
src/AdminUI/Services/DateTimeService.cs
src/ApiClient/Services/ILeaderboardService.cs
src/ApiClient/Services/IPrizeDrawService.cs
src/Application/Achievements/Command/ClaimSocialMediaAchievementForUser/ClaimSocialMediaAchievementForUserCommand.cs
src/Application/PrizeDraw/Queries/GetEligibleUsers.cs
src/Application/Rewards/Commands/ClaimRewardForUser/ClaimRewardForUserCommand.cs
src/Application/Rewards/Commands/CreatePendingRedemption/CreatePendingRedemptionCommand.cs
src/Application/Skills/Commands/UpsertSkill/UpsertSkillCommand.cs
src/Application/Users/Commands/UpsertUserSocialMediaId/UpsertUserSocialMediaIdCommand.cs
src/Common/DTOs/PrizeDraw/EligibleUsersViewModel.cs
src/Common/DTOs/PrizeDraw/GetEligibleUsersFilter.cs
src/Infrastructure/Persistence/Interceptors/AuditableEntitySaveChangesInterceptor.cs
src/WebAPI/Controllers/LeaderboardController.cs

Closes #1182 
The Today filter (and other filters) can be incorrect due to differences between the dates being stored in the DB (which should be UTC, but can vary) and the user's local time, where "today" would be a different time range. This PR:
1. Updates the prize draw filter to accept a date range that's converted from local time to UTC time, and updates the endpoint to work on these ranges instead.
2. Updates other uses in the code that's setting DateTime.Now rather than DateTime.UtcNow so the data going forward should be more consistent.
No

🐛 Admin/API | Fix prize draw date issues

---

.github/workflows/api-main.yml
src/AdminUI/Components/LoadingDialog.razor
src/AdminUI/Components/WinnerDialog.razor
src/AdminUI/Models/Winner.cs
src/AdminUI/Pages/PrizeDraw.razor
src/AdminUI/Program.cs
src/AdminUI/Services/PrizeDrawManager.cs
src/AdminUI/Services/WinnerStorageService.cs
src/AdminUI/wwwroot/index.html
src/Common/DTOs/PrizeDraw/GetEligibleUsersFilter.cs

Testing on Staging
Cleans up the prize draw page with some improvements and other behind the scenes changes after testing:
1. Cleans up the filtering so that optional fields are more obvious and grouped more logically.
2. Updates the timeframe dropdown so the items display better human-readable labels and are ordered chronologically rather than the odd ordering they are now.
3. Make the optional fields (achievement and top X) clearable.
4. Make the Top X a numeric field with a minimum of 1 that defaults to blank. Clearing this allows fetching with no limit, which is more obvious than having to set it to 0.
5. Moves the loading spinner to a modal rather than have it sit below …

♻️ Admin | Prize draw page improvements

---

src/MobileUI/Features/SocialMedia/AddSocialMediaPage.xaml
src/MobileUI/Features/SocialMedia/AddSocialMediaViewModel.cs

Closes #1293
Trims whitespace on the social media input when the input is unfocused and also when the user tries to submit.
No

🐛 Mobile | Trim whitespace on social media input

---

src/AdminUI/Shared/MainLayout.razor
src/AdminUI/wwwroot/.well-known/apple-app-site-association
src/ApiClient/Constants.cs
src/MobileUI/Platforms/Android/MainActivity.cs

Testing
1. Updates URL associations for app/universal links to only support the /redeem path, as this is the only path we want to navigate to the app currently.
2. Now defaults to generating QR codes using our domain by default, as we now have enough users on the latest version of the app.
3. Small tweak to the admin UI to not show "Admin Portal" as this can show briefly to the end user when navigating to one of these redeem URLs.
No

♻️ Admin/Mobile | Update URL associations

---

src/MobileUI/Features/Leaderboard/LeaderboardPage.xaml
src/MobileUI/Features/Leaderboard/LeaderboardViewModel.cs

Adam's comment here https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/1284#issuecomment-2933779604
Adds "Me" to the location button in the top right of the leaderboard page to make it clearer what the button actually does.
**✅ Figure: Button is now clearer**
No

♻️ Mobile | Show "Me" on location button

---

src/WebAPI/Filters/UrlBlockList.cs
src/WebAPI/Program.cs
src/WebAPI/Telemetry/WebApiTelemetryInitializer.cs

✏️ #1337 initial work to reduce the noise in Application Insights.
✏️ React with 204 on `/` URL and very simple URL blocking logic that waits a few seconds before responding 404. It also no longer logs blocked URLs as errors.
✏️ No.

💚 Reduce the 404 noise in application insights - part 1

---

src/WebAPI/Program.cs

✏️ System.NullReferenceException in AppInsights triggered by `await ctx.Response.CompleteAsync();` which should have worked ok.
✏️ `ctx.Response.StatusCode = StatusCodes.Status200OK;`
Locally, it works perfectly with either approach, and strangely enough, there are no issues with other endpoints that do the same thing.
✏️ No.

💚 Fixing `/` endpoint from 204 to 200 to fix a silent exception

---

src/Application/Common/Constants/CacheKeys.cs
src/Application/Rewards/Commands/ClaimReward/ClaimRewardCommand.cs
src/Infrastructure/Persistence/Configurations/AchievementConfiguration.cs
src/Infrastructure/Persistence/Configurations/RewardConfiguration.cs
src/Infrastructure/Persistence/Configurations/UserRewardConfiguration.cs
src/Infrastructure/Persistence/Migrations/20250702075823_ClaimRewardIndexes.Designer.cs
src/Infrastructure/Persistence/Migrations/20250702075823_ClaimRewardIndexes.cs

✏️ #1160 
✏️ Improved DB indexes and queries to fetch data for claiming rewards.
Original SQL query for the top-most active user returned 1000+ rows with ~42 columns! Now it will always return only 1 row.
The execution plan difference was done based on my account, which only had ~100 rows in the original query; however, the analysis shows very promising improvements. The query was handcrafted and ChatGPT o3 was used to verify the execution plan.
| Metric | Original plan – fan-out joins | After indexes – scalar sub-queries |
| --- | --- | --- |
| Rows returned to client | 93 detail rows (User × Rewards × Achievements) | 1 row (totals + flag)
| Sub-tree cost | 0.0652 | 0.0301  (- 54 …

⚡ Improve performance for claiming rewards

---

src/MobileUI/Features/Scanner/ScanPage.xaml.cs
src/MobileUI/Features/Scanner/ScanViewModel.cs

Closes #1374 
There seems to be an issue with the camera library on iOS where toggling the CameraEnabled value too quickly after the value was previously changed can cause the entire app to lock up for several seconds. One way to reproduce this is by going to the scanner, tapping My Code, tapping Scan and then soon after tapping one of the tabs at the bottom of the screen.
This change updates this toggling code to prevent this value from changing too quickly by adding a delay, which appears to resolve this issue.
No

🐛 Mobile | Fix camera toggle freezing the app

---

src/Application/Leaderboard/LeaderboardService.cs
src/Common/Utils/RegexHelpers.cs
src/MobileUI/Config/SocialMediaConfig.cs
src/MobileUI/Controls/Snackbar.xaml
src/MobileUI/DependencyInjection.cs
src/MobileUI/Features/Activity/ActivityPageViewModel.cs
src/MobileUI/Features/Leaderboard/LeaderViewModel.cs
src/MobileUI/Features/Profile/ProfileViewModelBase.cs
src/MobileUI/Features/SocialMedia/AddSocialMediaPage.xaml
src/MobileUI/Features/SocialMedia/AddSocialMediaPage.xaml.cs
src/MobileUI/Features/SocialMedia/AddSocialMediaViewModel.cs
src/MobileUI/MobileUI.csproj
src/MobileUI/Models/SocialMediaPlatform.cs

Closes #1292 
Updates the social media popup to be more intuitive and user friendly by only needing the username portion to be entered. The bottom shows a preview of the URL that can also be tapped if valid to test opening the link. The user can also paste in their full URL and it will automatically strip out just the necessary part.
Also improves the code a lot to be cleaner and improves error handling.
Also fixes a small issue with the snackbar showing a large outline that was introduced in .NET 9.
**Figure: Social media popup now only requires the username part of the URL**
**Figure: A preview of the link is shown that can be tapped to open**
> 3. Did you do pair or mob …

🐛 Mobile | Social media popup improvements

---

src/AdminUI/Helpers/DateTimeFormatter.cs
src/AdminUI/Pages/Notifications.razor
src/AdminUI/_Imports.razor

✏️ #1368 
✏️ Format rule https://www.ssw.com.au/rules/weekdays-on-date-selectors/ and takes the correct browser language format.
✏️ No.
**Figure: Australian format.**
**Figure: American format.**
**Figure: Chinese format.**

Add DateTimeFormatter for consistent date formatting in notifications
